"""Pure-Python verifier for leanVM execution proofs.

Single end-to-end test vector — a rec-aggregation proof over one XMSS
signature — is generated by the Rust side and stored under `target/`.
Run this script to verify it.

Setup (one-time):
    # Python venv + lean_spec (gives us KoalaBear `Fp` and the Poseidon1
    # permutation).
    uv venv .venv --python 3.12
    VIRTUAL_ENV=.venv uv pip install "git+https://github.com/leanEthereum/leanSpec.git"

    # Rust-side data (hardcoded soundness numbers + Poseidon round constants).
    cargo test --release -p lean_prover --test dump_whir_configs        -- --nocapture
    cargo test --release -p lean_prover --test dump_poseidon1_constants -- --nocapture

    # The end-to-end test vector (~17 MiB; takes a minute or two).
    cargo test --release -p lean_prover --test dump_zkvm_vector         -- --nocapture

Run:
    .venv/bin/python crates/lean_prover/verifier.py
"""

from __future__ import annotations

import functools
from dataclasses import dataclass
from typing import Sequence

from lean_spec.subspecs.koalabear import Fp, P
from lean_spec.subspecs.poseidon1 import PARAMS_16, Poseidon1

# WHIR builder constants (lean_prover/src/lib.rs).
WHIR_INITIAL_FOLDING_FACTOR = 7
WHIR_SUBSEQUENT_FOLDING_FACTOR = 5
MAX_NUM_VARIABLES_TO_SEND_COEFFS = 8
RS_DOMAIN_INITIAL_REDUCTION_FACTOR = 5

# Poseidon16 sponge parameters. The challenger uses the compression-with-
# domain-separator design: `state` is a RATE-sized buffer; `observe(chunk)`
# does `state ← permute(state || chunk)[:RATE]`; sampling re-permutes the
# state with a per-call domain separator.
RATE = 8
WIDTH = 16
CAPACITY = WIDTH - RATE
DIGEST_ELEMS = 8

# leanVM SNARK domain separator (lean_prover/src/lib.rs).
SNARK_DOMAIN_SEP = [
    Fp(v) for v in (
        130704175, 1303721200, 493664240, 1035493700,
        2063844858, 1410214009, 1938905908, 1696767928,
    )
]

# Bounds (lean_vm/src/core/constants.rs).
MIN_WHIR_LOG_INV_RATE, MAX_WHIR_LOG_INV_RATE = 1, 4
MIN_LOG_MEMORY_SIZE, MAX_LOG_MEMORY_SIZE = 16, 26
MIN_LOG_N_ROWS_PER_TABLE = 8
MIN_BYTECODE_LOG_SIZE = 8
BASE_TWO_ADICITY = 24  # KoalaBear

# WHIR config table dumped by `cargo test -p lean_prover --test dump_whir_configs`.
# Lives next to this file.
WHIR_CONFIGS_PATH = "whir_configs.json"



# ─── Error type + quintic extension field ──────────────────────────────────────────────────────────


class ProofError(Exception):
    """Mirrors backend::ProofError."""



# Quintic extension field: EF = Fp[X] / (X^5 + X^2 - 1)
# Reduction rule: X^5 = 1 - X^2.



class EF:
    """Quintic extension `Fp[X] / (X⁵ + X² − 1)`. Stored as 5 base coefficients;
    multiplication reduces with `X⁵ ≡ 1 − X²`."""

    __slots__ = ("c",)
    DIMENSION = 5

    def __init__(self, coeffs: Sequence[Fp]):
        assert len(coeffs) == 5
        self.c = tuple(coeffs)

    @staticmethod
    def zero() -> "EF":             return EF([Fp(0)] * 5)
    @staticmethod
    def one()  -> "EF":             return EF([Fp(1)] + [Fp(0)] * 4)
    @staticmethod
    def from_base(x: Fp) -> "EF":   return EF([x] + [Fp(0)] * 4)

    def __add__(self, o):
        if isinstance(o, Fp): return EF([self.c[0] + o, *self.c[1:]])
        return EF([a + b for a, b in zip(self.c, o.c)])
    def __sub__(self, o):
        if isinstance(o, Fp): return EF([self.c[0] - o, *self.c[1:]])
        return EF([a - b for a, b in zip(self.c, o.c)])
    def __neg__(self):              return EF([-a for a in self.c])
    __radd__ = __add__

    def __mul__(self, o):
        if isinstance(o, Fp): return EF([a * o for a in self.c])
        # Schoolbook degree-8 product, reduced with X^k = X^(k-5)·(1 − X²) for k ≥ 5.
        a, b = self.c, o.c
        prod = [Fp(0)] * 9
        for i in range(5):
            for j in range(5):
                prod[i + j] = prod[i + j] + a[i] * b[j]
        for k in range(8, 4, -1):
            coef = prod[k]
            prod[k - 5] = prod[k - 5] + coef
            prod[k - 3] = prod[k - 3] - coef
        return EF(prod[:5])
    __rmul__ = __mul__

    def __eq__(self, o):            return isinstance(o, EF) and self.c == o.c
    def __hash__(self):             return hash(self.c)
    def __repr__(self):             return f"EF({[int(x.value) for x in self.c]})"

    def inv(self) -> "EF":
        """Fermat: `a^(P⁵ − 2)`."""
        result, base, n = EF.one(), self, P ** 5 - 2
        while n > 0:
            if n & 1: result = result * base
            base = base * base
            n >>= 1
        return result



# ─── Poseidon16-based Challenger ──────────────────────────────────────────────────────────


_POSEIDON16 = Poseidon1(PARAMS_16)


def poseidon16_compress_in_place(state: list[Fp]) -> list[Fp]:
    """Davies-Meyer compression: `permute(state) + state` (length WIDTH)."""
    assert len(state) == WIDTH
    return [a + b for a, b in zip(_POSEIDON16.permute(state), state)]


def poseidon16_compress(left: Sequence[Fp], right: Sequence[Fp]) -> list[Fp]:
    """2:1 Merkle compression: top `DIGEST_ELEMS` of `permute(L || R) + (L || R)`."""
    return poseidon16_compress_in_place(list(left) + list(right))[:DIGEST_ELEMS]


def hash_slice(data: Sequence[Fp]) -> list[Fp]:
    """`symetric::hash_slice` with `WIDTH=16, RATE=OUT=8` (right-to-left absorb)."""
    assert len(data) % RATE == 0 and len(data) >= WIDTH
    state = poseidon16_compress_in_place(list(data[-WIDTH:]))
    for k in range(len(data) // RATE - 3, -1, -1):
        state = poseidon16_compress_in_place(state[:CAPACITY] + list(data[k * RATE : (k + 1) * RATE]))
    return state[:DIGEST_ELEMS]


class Challenger:
    """Compression-with-domain-separator Fiat-Shamir state.

    `state` is a length-`RATE` buffer; `observe(chunk)` does
    `state ← permute(state || chunk)[:RATE]`; sampling re-permutes the
    state with a per-call domain separator `[i, 0, …, 0]`."""

    def __init__(self) -> None:
        self.state: list[Fp] = [Fp(0)] * RATE

    def observe_many(self, scalars: Sequence[Fp]) -> None:
        for i in range(0, len(scalars), RATE):
            chunk = list(scalars[i : i + RATE])
            chunk += [Fp(0)] * (RATE - len(chunk))
            self.state = poseidon16_compress_in_place(self.state + chunk)[:RATE]

    def _sample_blocks(self, n_blocks: int) -> list[Fp]:
        """Run `n_blocks + 1` permutations with domain separators, advance the
        state to the last, return the first `n_blocks * RATE` scalars flat."""
        flat: list[Fp] = []
        for i in range(n_blocks + 1):
            ds = [Fp(i)] + [Fp(0)] * (RATE - 1)
            hashed = poseidon16_compress_in_place(ds + self.state)[:RATE]
            if i < n_blocks: flat.extend(hashed)
            else: self.state = hashed
        return flat

    def sample_ef_vec(self, n: int) -> list[EF]:
        flat = self._sample_blocks((n * EF.DIMENSION + RATE - 1) // RATE)[: n * EF.DIMENSION]
        return [EF(flat[i : i + EF.DIMENSION]) for i in range(0, len(flat), EF.DIMENSION)]

    def sample_ef(self) -> EF:
        return self.sample_ef_vec(1)[0]

    def sample_in_range(self, bits: int, n_samples: int) -> list[int]:
        """Truncate the low `bits` bits of `n_samples` field samples — matches
        `challenger::sample_in_range` (not perfectly uniform)."""
        assert bits < 31
        flat = self._sample_blocks((n_samples + RATE - 1) // RATE)[:n_samples]
        return [int(x.value) & ((1 << bits) - 1) for x in flat]



# ─── Proof container + VerifierState (transcript reader) ──────────────────────────────────────────────────────────


@dataclass
class MerkleOpening:
    """Restored Merkle opening: matches fiat_shamir::transcript::MerkleOpening."""

    leaf_data: list[Fp]
    path: list[list[Fp]]  # each sibling is a length-DIGEST_ELEMS digest


@dataclass
class Proof:
    """Mirrors `backend::RawProof`. `transcript` is the flat raw transcript
    (every absorbed group padded to a multiple of RATE with zeros — the format
    the zkDSL recursion verifier reads). `merkle_openings` is the list of
    already-restored openings in consumption order."""

    transcript: list[Fp]
    merkle_openings: list[MerkleOpening]


class VerifierState:
    """Drives the Fiat-Shamir transcript: reads scalars from `proof.transcript`,
    samples challenges from the challenger, yields restored Merkle openings.

    Every read pads to RATE — `n` real scalars are consumed as
    `next_multiple_of(n, RATE)` raw scalars (trailing positions must be zero),
    and the full RATE-aligned chunk is what the challenger absorbs."""

    def __init__(self, proof: Proof) -> None:
        self.challenger = Challenger()
        self.transcript = list(proof.transcript)
        self.openings = list(proof.merkle_openings)
        self.offset = 0
        self.open_idx = 0

    def _read_padded(self, n: int) -> list[Fp]:
        n_pad = -(-n // RATE) * RATE  # next multiple of RATE
        if self.offset + n_pad > len(self.transcript):
            raise ProofError("ExceededTranscript")
        chunk = self.transcript[self.offset : self.offset + n_pad]
        self.offset += n_pad
        if any(int(chunk[i].value) for i in range(n, n_pad)):
            raise ProofError("InvalidTranscript: non-zero padding")
        self.challenger.observe_many(chunk)
        return chunk

    def observe_scalars(self, scalars: Sequence[Fp]) -> None:
        self.challenger.observe_many(list(scalars))

    def next_base_scalars_vec(self, n: int) -> list[Fp]:
        return self._read_padded(n)[:n]

    def next_extension_scalars_vec(self, n: int) -> list[EF]:
        flat = self.next_base_scalars_vec(n * EF.DIMENSION)
        return [EF(flat[i : i + EF.DIMENSION]) for i in range(0, len(flat), EF.DIMENSION)]

    def next_extension_scalar(self) -> EF:           return self.next_extension_scalars_vec(1)[0]
    def sample(self) -> EF:                          return self.challenger.sample_ef()
    def sample_vec(self, n: int) -> list[EF]:        return self.challenger.sample_ef_vec(n)
    def sample_in_range(self, b: int, n: int) -> list[int]: return self.challenger.sample_in_range(b, n)

    def next_merkle_opening(self) -> MerkleOpening:
        if self.open_idx >= len(self.openings):
            raise ProofError("ExceededTranscript: no more Merkle openings")
        self.open_idx += 1
        return self.openings[self.open_idx - 1]

    def check_pow_grinding(self, bits: int) -> None:
        """Grinding witness is `[witness, 0, …, 0]` (RATE-padded)."""
        if bits == 0: return
        self._read_padded(1)
        if int(self.challenger.state[0].value) & ((1 << bits) - 1) != 0:
            raise ProofError("InvalidGrindingWitness")



# ─── Small helpers (Bytecode metadata, EF utilities, log2, padding) ──────────────────────────────────────────────


@dataclass
class Bytecode:
    """What `verify_execution` needs about a bytecode program."""
    hash: list[Fp]
    log_size: int


# Multiplicative inverse of 2 in Fp (KoalaBear). Used to halve EF elements.
_INV_TWO = Fp(pow(2, P - 2, P))


def log2_ceil_usize(x: int) -> int:
    return 0 if x <= 1 else (x - 1).bit_length()


def log2_strict_usize(x: int) -> int:
    assert x > 0 and (x & (x - 1)) == 0, f"{x} is not a power of two"
    return x.bit_length() - 1


def padd_with_zero_to_next_power_of_two(values: Sequence[Fp]) -> list[Fp]:
    if not values:
        return [Fp(0)]
    n = 1 << log2_ceil_usize(len(values))
    return list(values) + [Fp(0)] * (n - len(values))


# ─── Merkle path verify ──────────────────────────────────


def merkle_verify_path(
    commit: list[Fp],
    log_height: int,
    index: int,
    opened_values: Sequence[Fp],
    opening_proof: Sequence[list[Fp]],
) -> bool:
    """Hash the leaf, walk up `log_height` siblings, compare to the commitment."""
    if len(opening_proof) != log_height:
        return False
    cur = hash_slice(list(opened_values))
    for sibling in opening_proof:
        cur = poseidon16_compress(cur, sibling) if index & 1 == 0 else poseidon16_compress(sibling, cur)
        index >>= 1
    return list(commit) == list(cur)



# ─── WHIR polynomial primitives (poly + whir crates) ──────────────────────────────────────────────────────────


def expand_from_univariate(x: EF, num_variables: int) -> list[EF]:
    """`[x, x², x⁴, …, x^(2^(n−1))]` — `MultilinearPoint::expand_from_univariate`."""
    out, cur = [], x
    for _ in range(num_variables):
        out.append(cur)
        cur = cur * cur
    return out


def eq_poly_outside(a: Sequence[EF], b: Sequence[EF]) -> EF:
    """`Π (1 − a_i − b_i + 2·a_i·b_i)` — multilinear `eq` polynomial."""
    assert len(a) == len(b)
    one, acc = EF.one(), EF.one()
    for x, y in zip(a, b):
        xy = x * y
        acc = acc * (one + xy + xy - x - y)
    return acc


def next_mle(x: Sequence[EF], y: Sequence[EF]) -> EF:
    """The "next-row" weight `ν(x, y)`: multilinear extension of `y = x + 1`
    (big-endian, mod `2^n`). Sums one term per "carry boundary" position plus
    the all-ones wraparound `Π x_i · y_i`."""
    assert len(x) == len(y)
    one = EF.one()
    # Prefix of `eq(x_i, y_i)` and suffix of `Π x_i · (1 − y_i)` (the low-bits term).
    n = len(x)
    eq_prefix = [one]
    for i in range(n):
        eq_prefix.append(eq_prefix[i] * (x[i] * y[i] + (one - x[i]) * (one - y[i])))
    low_suffix = [one] * (n + 1)
    for i in range(n - 1, -1, -1):
        low_suffix[i] = low_suffix[i + 1] * x[i] * (one - y[i])
    s = EF.zero()
    for i in range(n):
        s = s + eq_prefix[i] * (one - x[i]) * y[i] * low_suffix[i + 1]
    prod = one
    for v in list(x) + list(y):
        prod = prod * v
    return s + prod


def eval_multilinear_evals(evals: Sequence[EF], point: Sequence[EF]) -> EF:
    """Evaluate a multilinear in evaluation form (length `2^n`) at `point ∈ EF^n`.
    Big-endian indexing — fold variables last-to-first."""
    assert len(evals) == 1 << len(point)
    cur = list(evals)
    for r in reversed(point):
        cur = [cur[j] + (cur[j + 1] - cur[j]) * r for j in range(0, len(cur), 2)]
    return cur[0]


def eval_mle_base_at_ef(base_evals: Sequence[int], point: Sequence[EF]) -> EF:
    """Same fold as `eval_multilinear_evals`, specialized for base-field evals.

    Uses numpy to skip per-scalar Python/`Fp` wrapper overhead — the bytecode
    multilinear is a 2²²-entry fold, far too big for the generic path.
    """
    import numpy as np
    assert len(base_evals) == 1 << len(point)
    pt = [tuple(int(ci.value) for ci in p.c) for p in point]
    cur = np.asarray(base_evals, dtype=np.int64) % P
    # First round: base → EF.  a + (b-a)*r, with r ∈ EF, a,b ∈ base.
    a, b = cur[0::2], cur[1::2]
    d = (b - a) % P
    r = pt[-1]
    cur = np.stack(
        [(a + d * r[0]) % P, *[(d * r[k]) % P for k in range(1, 5)]],
        axis=1,
    )
    # Remaining rounds: EF × EF.  Schoolbook product reduced mod X^5+X^2-1
    # (using X^5≡1-X², X^6≡X-X³, X^7≡X²-X⁴, X^8≡X³+X²-1).
    # Reduce every multiply before summing to stay inside int64.
    for r0, r1, r2, r3, r4 in (pt[i] for i in range(len(pt) - 2, -1, -1)):
        a, b = cur[0::2], cur[1::2]
        d = (b - a) % P
        d0, d1, d2, d3, d4 = d[:, 0], d[:, 1], d[:, 2], d[:, 3], d[:, 4]
        m = lambda x, y: (x * y) % P
        p0 = m(d0, r0)
        p1 = (m(d0, r1) + m(d1, r0)) % P
        p2 = (m(d0, r2) + m(d1, r1) + m(d2, r0)) % P
        p3 = (m(d0, r3) + m(d1, r2) + m(d2, r1) + m(d3, r0)) % P
        p4 = (m(d0, r4) + m(d1, r3) + m(d2, r2) + m(d3, r1) + m(d4, r0)) % P
        p5 = (m(d1, r4) + m(d2, r3) + m(d3, r2) + m(d4, r1)) % P
        p6 = (m(d2, r4) + m(d3, r3) + m(d4, r2)) % P
        p7 = (m(d3, r4) + m(d4, r3)) % P
        p8 = m(d4, r4)
        cur = np.stack([
            (a[:, 0] + p0 + p5 - p8) % P,
            (a[:, 1] + p1 + p6) % P,
            (a[:, 2] + p2 - p5 + p7 + p8) % P,
            (a[:, 3] + p3 - p6 + p8) % P,
            (a[:, 4] + p4 - p7) % P,
        ], axis=1)
    return EF([Fp(int(v)) for v in cur[0]])


def eval_multilinear_coeffs(coeffs: Sequence[EF], point: Sequence[EF]) -> EF:
    """`Σ_b c_b · Π_i x_i^(b_i)` in the standard multilinear coefficient basis."""
    assert len(coeffs) == 1 << len(point)
    if not point:
        return coeffs[0]
    half = len(coeffs) // 2
    lo = eval_multilinear_coeffs(coeffs[:half], point[1:])
    hi = eval_multilinear_coeffs(coeffs[half:], point[1:])
    return lo + hi * point[0]


@dataclass
class SparseValue:
    selector: int
    value: EF


@dataclass
class SparseStatement:
    """A claim with a multilinear `point` over the last `len(point)` variables
    and one or more `(selector, value)` pairs indexing the leading selector
    bits. `is_next` swaps the eq-weight for a "next-row" weight (`next_mle`)."""

    total_num_variables: int
    point: list[EF]
    values: list[SparseValue]
    is_next: bool = False

    @property
    def selector_num_variables(self) -> int:
        return self.total_num_variables - len(self.point)

    @staticmethod
    def dense(point: list[EF], value: EF) -> "SparseStatement":
        return SparseStatement(len(point), point, [SparseValue(0, value)])

    @staticmethod
    def unique_value(total: int, index: int, value: EF) -> "SparseStatement":
        return SparseStatement(total, [], [SparseValue(index, value)])

    @staticmethod
    def new_next(total: int, point: list[EF], values: list[SparseValue]) -> "SparseStatement":
        return SparseStatement(total, point, values, is_next=True)



# ─── WHIR config helpers: derive integer-only parameters from the trimmed JSON ──────────────────────────────────────────────────────────


def whir_folding_factor_at_round(r: int) -> int:
    return WHIR_INITIAL_FOLDING_FACTOR if r == 0 else WHIR_SUBSEQUENT_FOLDING_FACTOR


def whir_n_rounds_and_final_sumcheck(num_variables: int) -> tuple[int, int]:
    """FoldingFactor::compute_number_of_rounds with default (7, 5, max_send=8).
    Returns `(n_rounds, final_sumcheck_rounds)`."""
    nv = num_variables - WHIR_INITIAL_FOLDING_FACTOR
    if nv < MAX_NUM_VARIABLES_TO_SEND_COEFFS:
        return 0, nv
    n = -(-(nv - MAX_NUM_VARIABLES_TO_SEND_COEFFS) // WHIR_SUBSEQUENT_FOLDING_FACTOR)
    return n, nv - n * WHIR_SUBSEQUENT_FOLDING_FACTOR


def whir_log_inv_rate_at(start_rate: int, r: int) -> int:
    """Initial rate, then each round adds `folding_factor − rs_reduction`."""
    return start_rate + r * (WHIR_SUBSEQUENT_FOLDING_FACTOR - 1) + (
        WHIR_INITIAL_FOLDING_FACTOR - RS_DOMAIN_INITIAL_REDUCTION_FACTOR if r >= 1 else 0
    )


def whir_log_domain_size_at(num_variables: int, start_rate: int, r: int) -> int:
    """`log₂(domain_size)` going into round `r`: starts at `num_vars + rate`
    and shrinks by the per-round RS reduction (`5` at round 0, `1` thereafter)."""
    return num_variables + start_rate - (RS_DOMAIN_INITIAL_REDUCTION_FACTOR + r - 1 if r >= 1 else 0)


# KoalaBear two-adic generators: index `bits` is the primitive 2^bits-th root
# of unity (canonical-form u32 values, mirrors `TWO_ADIC_GENERATORS`).
KB_TWO_ADIC_GENERATORS: list[int] = [
    0x1, 0x7F000000, 0x7E010002, 0x6832FE4A, 0x08DBD69C, 0x0A28F031, 0x5C4A5B99,
    0x29B75A80, 0x17668B8A, 0x27AD539B, 0x334D48C7, 0x7744959C, 0x768FC6FA,
    0x303964B2, 0x3E687D4D, 0x45A60E61, 0x6E2F4D7A, 0x163BD499, 0x6C4A8A45,
    0x143EF899, 0x514DDCAD, 0x484EF19B, 0x205D63C3, 0x68E7DD49, 0x6AC49F88,
]


def two_adic_generator(bits: int) -> Fp:
    return Fp(KB_TWO_ADIC_GENERATORS[bits])


@dataclass(frozen=True)
class WhirRoundConfig:
    num_queries: int
    ood_samples: int
    query_pow_bits: int
    folding_pow_bits: int


@dataclass(frozen=True)
class WhirConfig:
    log_inv_rate: int
    num_variables: int
    commitment_ood_samples: int
    starting_folding_pow_bits: int
    final_queries: int
    final_query_pow_bits: int
    rounds: tuple[WhirRoundConfig, ...]


@functools.cache
def whir_config(log_inv_rate: int, num_variables: int) -> WhirConfig:
    """Loads the Rust-dumped JSON (float-derived query/OOD/grinding numbers).
    Everything else is recomputed on the fly via the helpers above."""
    import json
    from pathlib import Path
    raw = json.loads(Path(__file__).with_name(WHIR_CONFIGS_PATH).read_text())
    for c in raw:
        if (c["log_inv_rate"], c["num_variables"]) == (log_inv_rate, num_variables):
            return WhirConfig(
                **{k: c[k] for k in WhirConfig.__annotations__ if k != "rounds"},
                rounds=tuple(WhirRoundConfig(**r) for r in c["rounds"]),
            )
    raise KeyError(
        f"No WHIR config for (log_inv_rate={log_inv_rate}, num_variables={num_variables}). "
        "Regenerate with: cargo test -p lean_prover --test dump_whir_configs"
    )



# ─── WHIR verifier (port of crates/whir/src/verify.rs) ──────────────────────────────────────────────────────────


@dataclass
class ParsedCommitment:
    num_variables: int
    root: list[Fp]              # length DIGEST_ELEMS
    ood_points: list[EF]
    ood_answers: list[EF]

    def oods_constraints(self) -> list[SparseStatement]:
        return [
            SparseStatement.dense(expand_from_univariate(p, self.num_variables), ev)
            for p, ev in zip(self.ood_points, self.ood_answers)
        ]


def parsed_commitment_parse(state: VerifierState, num_variables: int, ood_samples: int) -> ParsedCommitment:
    root = state.next_base_scalars_vec(DIGEST_ELEMS)
    ood_points = state.sample_vec(ood_samples) if ood_samples else []
    ood_answers = state.next_extension_scalars_vec(ood_samples) if ood_samples else []
    return ParsedCommitment(num_variables, root, ood_points, ood_answers)


@dataclass
class Evaluation:
    """Claim that a multilinear evaluates to `value` at `point`."""
    point: list[EF]
    value: EF


def _eval_univariate(coeffs: list[EF], x: EF) -> EF:
    """Horner: c[0] + c[1]*x + c[2]*x^2 + ..."""
    acc = EF.zero()
    for c in reversed(coeffs):
        acc = acc * x + c
    return acc


def verify_sumcheck(
    state: VerifierState,
    target: EF,
    n_vars: int,
    degree: int,
    pow_bits: int = 0,
) -> "Evaluation":
    """Read `n_vars` round polynomials in univariate basis (`degree + 1` coeffs
    each). Per round: check `h(0) + h(1) == target`, optional PoW grinding,
    sample a challenge, fold the target into `h(challenge)`."""
    point: list[EF] = []
    for _ in range(n_vars):
        coeffs = state.next_extension_scalars_vec(degree + 1)
        s = coeffs[0]  # h(0) + h(1) = coeffs[0] + Σ coeffs.
        for c in coeffs:
            s = s + c
        if s != target:
            raise ProofError("Sumcheck identity failed: h(0) + h(1) != target")
        state.check_pow_grinding(pow_bits)
        r = state.sample()
        point.append(r)
        target = _eval_univariate(coeffs, r)
    return Evaluation(point=point, value=target)


def combine_constraints(
    state: VerifierState,
    target: EF,
    constraints: list[SparseStatement],
) -> tuple[EF, list[EF]]:
    """Linear combination of constraint values by random `γ` powers. Returns
    the updated target and the per-value combination weights `[1, γ, γ², ...]`."""
    gamma: EF = state.sample()
    combo = [EF.one()]
    for smt in constraints:
        for v in smt.values:
            target = target + combo[-1] * v.value
            combo.append(combo[-1] * gamma)
    combo.pop()
    return target, combo


def verify_stir_challenges(
    state: VerifierState,
    cfg: WhirConfig,
    round_index: int,
    num_variables: int,
    folding_factor: int,
    num_queries: int,
    query_pow_bits: int,
    commitment: ParsedCommitment,
    folding_randomness: list[EF],
) -> list[SparseStatement]:
    """Read `num_queries` Merkle openings, fold each answer at
    `folding_randomness`, and emit a dense STIR constraint per query."""
    log_domain = whir_log_domain_size_at(cfg.num_variables, cfg.log_inv_rate, round_index)
    log_height = log_domain - folding_factor
    gen = two_adic_generator(log_height)

    state.check_pow_grinding(query_pow_bits)
    indices = state.sample_in_range(log_height, num_queries)

    def pack_answers(leaf: list[Fp]) -> list[EF]:
        # Round 0 leaves are base-field; later rounds carry packed EF (5 base → 1 EF).
        if round_index == 0:
            return [EF.from_base(f) for f in leaf]
        return [EF(leaf[i : i + EF.DIMENSION]) for i in range(0, len(leaf), EF.DIMENSION)]

    constraints: list[SparseStatement] = []
    for idx in indices:
        op = state.next_merkle_opening()
        if not merkle_verify_path(commitment.root, log_height, idx, op.leaf_data, op.path):
            raise ProofError("Merkle verification failed")
        fold = eval_multilinear_evals(pack_answers(op.leaf_data), folding_randomness)
        ef_pt = EF.from_base(Fp(pow(int(gen.value), idx, P)))
        constraints.append(SparseStatement.dense(expand_from_univariate(ef_pt, num_variables), fold))
    return constraints


def verify_constraint_coeffs(constraint: SparseStatement, coeffs: list[EF]) -> bool:
    """Checks `constraint.point == [α, α², α⁴, …]` and that the univariate
    `Σ coeffs[i] · α^i` matches every claimed value."""
    assert constraint.selector_num_variables == 0
    alpha = constraint.point[0]
    if any(a * a != b for a, b in zip(constraint.point, constraint.point[1:])):
        return False
    univ_eval = _eval_univariate(coeffs, alpha)
    return all(univ_eval == v.value for v in constraint.values)


def eval_constraints_poly(
    constraints: list[tuple[list[EF], list[SparseStatement]]],
    point: list[EF],
) -> EF:
    """Per-round `(combination_weights, statements)`: at each round we slice
    `point` by the previous round's folding factor, then sum
    `lagrange(selector) · common_weight(smt.point, inner_pt) · γ^i` over all
    `(smt, value)` pairs."""
    value = EF.zero()
    pt = list(point)
    for round_idx, (randomness, smts) in enumerate(constraints):
        if round_idx > 0:
            pt = pt[whir_folding_factor_at_round(round_idx - 1):]
        i = 0
        for smt in smts:
            inner_pt = pt[len(pt) - len(smt.point):]
            common = next_mle(smt.point, inner_pt) if smt.is_next else eq_poly_outside(smt.point, inner_pt)
            sel_n = smt.selector_num_variables
            for v in smt.values:
                lagrange = EF.one()
                for j in range(sel_n):
                    bit = (v.selector >> (sel_n - 1 - j)) & 1
                    lagrange = lagrange * (pt[j] if bit else (EF.one() - pt[j]))
                value = value + lagrange * common * randomness[i]
                i += 1
        assert i == len(randomness)
    return value


def whir_verify(
    state: VerifierState,
    cfg: WhirConfig,
    parsed_commitment: ParsedCommitment,
    statement: list[SparseStatement],
) -> list[EF]:
    for s in statement:
        assert s.total_num_variables == parsed_commitment.num_variables

    n_rounds, final_sumcheck_rounds = whir_n_rounds_and_final_sumcheck(cfg.num_variables)
    round_constraints: list[tuple[list[EF], list[SparseStatement]]] = []
    round_folding: list[list[EF]] = []
    target = EF.zero()

    def step(constraints: list[SparseStatement], n_fold: int, pow_bits: int) -> None:
        nonlocal target
        new_target, combo = combine_constraints(state, target, constraints)
        round_constraints.append((combo, constraints))
        sc = verify_sumcheck(state, new_target, n_fold, 2, pow_bits)
        round_folding.append(sc.point)
        target = sc.value

    # Initial: OODS + caller statement, then run the first folding sumcheck.
    step(parsed_commitment.oods_constraints() + statement,
         whir_folding_factor_at_round(0), cfg.starting_folding_pow_bits)

    # Per-round loop: new commitment → STIR → combine → fold sumcheck.
    prev_commitment = parsed_commitment
    nvars_round = cfg.num_variables
    for r in range(n_rounds):
        rp = cfg.rounds[r]
        nvars_round -= whir_folding_factor_at_round(r)
        new_commitment = parsed_commitment_parse(state, nvars_round, rp.ood_samples)
        stir = verify_stir_challenges(
            state, cfg, r, nvars_round,
            whir_folding_factor_at_round(r), rp.num_queries, rp.query_pow_bits,
            prev_commitment, round_folding[-1],
        )
        step(new_commitment.oods_constraints() + stir,
             whir_folding_factor_at_round(r + 1), rp.folding_pow_bits)
        prev_commitment = new_commitment

    # Final round: send poly in coefficient form, verify STIR queries against it.
    n_vars_final = nvars_round - whir_folding_factor_at_round(n_rounds)
    final_coeffs = state.next_extension_scalars_vec(1 << n_vars_final)
    final_stir = verify_stir_challenges(
        state, cfg, n_rounds, n_vars_final,
        whir_folding_factor_at_round(n_rounds), cfg.final_queries, cfg.final_query_pow_bits,
        prev_commitment, round_folding[-1],
    )
    for smt in final_stir:
        if not verify_constraint_coeffs(smt, final_coeffs):
            raise ProofError("Final STIR constraint mismatch")

    # Final sumcheck — closes the protocol against the constraint-weights MLE.
    final_sc = verify_sumcheck(state, target, final_sumcheck_rounds, 2)
    round_folding.append(final_sc.point)

    folding_flat = [r for chunk in round_folding for r in chunk]
    eval_weights = eval_constraints_poly(round_constraints, folding_flat)
    final_value = eval_multilinear_coeffs(final_coeffs, list(reversed(final_sc.point)))
    if final_sc.value != eval_weights * final_value:
        raise ProofError("WHIR final sumcheck check failed")

    return folding_flat



# ─── Table metadata (mirror of lean_vm::tables::table_trait) ──────────────────────────────────────────────────────────


@dataclass(frozen=True)
class TableMeta:
    """The bits of `lean_vm::Table` the verifier consumes. Each lookup is a
    `(index_column, value_columns)` pair (mirrors `LookupIntoMemory`)."""

    name: str
    n_columns: int
    bus_direction: str         # "Pull" or "Push"
    lookups: tuple[tuple[int, tuple[int, ...]], ...]


def tables_from_json(obj: list[dict]) -> list[TableMeta]:
    return [
        TableMeta(
            name=t["name"],
            n_columns=int(t["n_columns"]),
            bus_direction=t["bus"]["direction"],
            lookups=tuple((int(l["index"]), tuple(int(v) for v in l["values"])) for l in t["lookups"]),
        )
        for t in obj
    ]



# ─── Stacked PCS — port of sub_protocols/stacked_pcs.rs ──────────────────────────────────────────────────────────


def compute_stacked_n_vars(
    log_memory: int,
    log_bytecode: int,
    table_log_heights: dict[str, int],
    table_n_columns: dict[str, int],
) -> int:
    """`log₂` of the stacked polynomial length: 2·memory + bytecode-acc (padded
    to the tallest table) + Σ per-table `n_columns × 2^log_n_rows`."""
    max_h = max(table_log_heights.values())
    total = (2 << log_memory) + (1 << max(log_bytecode, max_h))
    total += sum(table_n_columns[n] << h for n, h in table_log_heights.items())
    return log2_ceil_usize(total)


def stacked_pcs_global_statements(
    stacked_n_vars: int,
    memory_n_vars: int,
    bytecode_n_vars: int,
    previous_statements: list[SparseStatement],
    table_log_heights: dict[str, int],
    committed_statements: dict[str, list[tuple[list[EF], dict[int, EF], dict[int, EF]]]],
    tables: dict[str, TableMeta],
    constants: dict,
) -> list[SparseStatement]:
    """Stacks the per-table column claims into the global statement list passed to
    `WhirConfig::verify`. Tables are processed in descending-height order.
    """
    assert len(table_log_heights) == len(committed_statements)
    tables_sorted = sort_tables_by_height(table_log_heights)

    out = list(previous_statements)
    offset = (2 << memory_n_vars) + (1 << max(bytecode_n_vars, tables_sorted[0][1]))
    col_pc = constants["col_pc"]

    def values_at(d: dict[int, EF], n_vars: int) -> list[SparseValue]:
        # Rust uses BTreeMap → ascending-key iteration; Python dicts are
        # insertion-ordered, so we sort explicitly here.
        return [SparseValue((offset >> n_vars) + i, v) for i, v in sorted(d.items())]

    for name, n_vars in tables_sorted:
        if name == "execution":
            # PC column: first row pinned to `starting_pc`, last row to `ending_pc`.
            for idx_in_col, pc_value in [(0, constants["starting_pc"]), ((1 << n_vars) - 1, constants["ending_pc"])]:
                out.append(SparseStatement.unique_value(
                    stacked_n_vars, offset + (col_pc << n_vars) + idx_in_col, EF.from_base(Fp(pc_value)),
                ))

        for (point, eq_values, next_values) in committed_statements[name]:
            if next_values:
                out.append(SparseStatement.new_next(stacked_n_vars, list(point), values_at(next_values, n_vars)))
            out.append(SparseStatement(stacked_n_vars, list(point), values_at(eq_values, n_vars)))

        offset += tables[name].n_columns << n_vars

    return out


def stacked_pcs_parse_commitment(
    state: VerifierState,
    log_inv_rate: int,
    log_memory: int,
    log_bytecode: int,
    table_log_heights: dict[str, int],
    table_n_columns: dict[str, int],
) -> ParsedCommitment:
    """Validate sizing invariants (memory ≥ execution ≥ all other tables,
    stacked-poly fits the WHIR domain bound), then parse the commitment."""
    exec_log = table_log_heights["execution"]
    if log_memory < exec_log or exec_log < max(table_log_heights.values()):
        raise ProofError("InvalidProof: memory or execution table size invariants broken")
    stacked_n_vars = compute_stacked_n_vars(log_memory, log_bytecode, table_log_heights, table_n_columns)
    if stacked_n_vars > BASE_TWO_ADICITY + WHIR_INITIAL_FOLDING_FACTOR - log_inv_rate:
        raise ProofError("InvalidProof: stacked_n_vars exceeds WHIR domain bound")
    cfg = whir_config(log_inv_rate, stacked_n_vars)
    return parsed_commitment_parse(state, stacked_n_vars, cfg.commitment_ood_samples)



# ─── GKR-quotient verifier (port of `sub_protocols::quotient_gkr`) ──────────────────────────────────────────────────────────
# Verifies `Σ nᵢ/dᵢ` via a layered sumcheck.


N_VARS_TO_SEND_GKR_COEFFS = 5


def verify_gkr_quotient(state: VerifierState, n_vars: int) -> tuple[EF, list[EF], EF, EF]:
    """Returns `(quotient, point, claim_num, claim_den)`. Reads the top-level
    coefficients, then collapses one variable per layer with a degree-3
    sumcheck on `n·d_r + n_r·d` plus the next (num, den) random combination."""
    assert n_vars > N_VARS_TO_SEND_GKR_COEFFS

    nums = state.next_extension_scalars_vec(1 << N_VARS_TO_SEND_GKR_COEFFS)
    dens = state.next_extension_scalars_vec(1 << N_VARS_TO_SEND_GKR_COEFFS)
    quotient = EF.zero()
    for n, d in zip(nums, dens):
        quotient = quotient + n * d.inv()

    point = state.sample_vec(N_VARS_TO_SEND_GKR_COEFFS)
    claim_num = eval_multilinear_evals(nums, point)
    claim_den = eval_multilinear_evals(dens, point)

    for layer_n_vars in range(N_VARS_TO_SEND_GKR_COEFFS, n_vars):
        alpha = state.sample()
        sc = verify_sumcheck(state, claim_num + alpha * claim_den, layer_n_vars, 3)
        sc_point = list(reversed(sc.point))
        # Inner evaluations: (n_left, n_right, d_left, d_right) at sc.point.
        nl, nr, dl, dr = state.next_extension_scalars_vec(4)
        # Sumcheck identity: eq(point, sc_point) · (α·dl·dr + (nl·dr + nr·dl)).
        if sc.value != eq_poly_outside(point, sc_point) * (alpha * dl * dr + nl * dr + nr * dl):
            raise ProofError("GKR step: postponed value mismatch")
        beta = state.sample()
        one_minus = EF.one() - beta
        claim_num = one_minus * nl + beta * nr
        claim_den = one_minus * dl + beta * dr
        point = sc_point + [beta]

    return quotient, point, claim_num, claim_den



# ─── Logup helpers (utils + poly) ──────────────────────────────────────────────────────────


def to_big_endian_in_field(value: int, bit_count: int) -> list[EF]:
    """`bit_count` bits of `value` MSB-first, each as `EF::ZERO`/`EF::ONE`."""
    return [EF.one() if (value >> (bit_count - 1 - i)) & 1 else EF.zero() for i in range(bit_count)]


def from_end(seq: Sequence, n: int) -> list:
    """Last `n` elements of `seq`."""
    return list(seq[len(seq) - n :]) if n else []


def mle_of_01234567_etc(point: Sequence[EF]) -> EF:
    """MLE of `f(i) = i` (big-endian) at `point`."""
    if not point:
        return EF.zero()
    e = mle_of_01234567_etc(point[1:])
    return e + point[0] * EF.from_base(Fp(1 << (len(point) - 1)))


def mle_of_zeros_then_ones(n_zeros: int, point: Sequence[EF]) -> EF:
    """MLE of `[0]*n_zeros ++ [1]*(2^len(point) − n_zeros)` at `point`."""
    n_values = 1 << len(point)
    assert n_zeros <= n_values
    if n_zeros == 0:        return EF.one()
    if n_zeros == n_values: return EF.zero()
    half, tail = n_values >> 1, point[1:]
    if n_zeros < half:
        return (EF.one() - point[0]) * mle_of_zeros_then_ones(n_zeros, tail) + point[0]
    return point[0] * mle_of_zeros_then_ones(n_zeros - half, tail)


def finger_print(table: Fp, data: Sequence[EF], alphas_eq_poly: Sequence[EF]) -> EF:
    """`Σᵢ αᵢ · dataᵢ + α_last · table` — Reed-Solomon-style fingerprint."""
    assert len(alphas_eq_poly) > len(data)
    acc = EF.zero()
    for a, d in zip(alphas_eq_poly, data):
        acc = acc + a * d
    return acc + alphas_eq_poly[-1] * EF.from_base(table)


def sort_tables_by_height(table_log_heights: dict[str, int]) -> list[tuple[str, int]]:
    """Descending by height, alphabetical on ties (matches Rust `BTreeMap`)."""
    return sorted(sorted(table_log_heights.items()), key=lambda kv: -kv[1])


def eval_eq(point: Sequence[EF]) -> list[EF]:
    """Length-`2^n` evaluation table of `eq(point, ·)`: big-endian-bit-indexed
    `Πⱼ (point[j] if bitⱼ(i) else 1 − point[j])`."""
    out = [EF.one()]
    for p in point:
        out = [w for v in out for w in (v * (EF.one() - p), v * p)]
    return out



# ─── Generic logup verifier — port of sub_protocols/logup.rs::verify_generic_logup ──────────────────────────────────────────────────────────


@dataclass
class GenericLogupStatements:
    memory_and_acc_point: list[EF]
    value_memory: EF
    value_memory_acc: EF
    bytecode_and_acc_point: list[EF]
    value_bytecode_acc: EF
    bus_numerators_values: dict[str, EF]
    bus_denominators_values: dict[str, EF]
    gkr_point: list[EF]
    columns_values: dict[str, dict[int, EF]]


def verify_generic_logup(
    state: VerifierState,
    c: EF,
    alphas: list[EF],
    alphas_eq_poly: list[EF],
    log_memory: int,
    bytecode_multilinear: list[int],
    table_log_heights: dict[str, int],
    tables: dict[str, TableMeta],
    constants: dict,
) -> GenericLogupStatements:
    """Run the GKR-quotient protocol and reconstruct numerator/denominator
    sums section by section (memory / bytecode / per-table). Each section
    contributes a `pref · (num_term, den_term)` pair to the running totals."""
    n_instr_cols   = constants["n_instruction_columns"]
    n_runtime_cols = constants["n_runtime_columns"]
    col_pc         = constants["col_pc"]
    dom_mem        = Fp(constants["logup_memory_domainsep"])
    dom_byte       = Fp(constants["logup_bytecode_domainsep"])

    tables_sorted = sort_tables_by_height(table_log_heights)
    log_bytecode  = log2_strict_usize(len(bytecode_multilinear) // (1 << log2_ceil_usize(n_instr_cols)))
    log_instr     = log2_ceil_usize(n_instr_cols)
    log_n_cycles  = table_log_heights["execution"]

    # Total active length: memory + max(bytecode, tallest table) + execution
    # cycles + Σ per-table (lookup arity sum + 1 bus column) × 2^log_n_rows.
    table_cols = lambda n: sum(len(vs) for _, vs in tables[n].lookups) + 1
    total_active_len = (
        (1 << log_memory) + max(1 << log_bytecode, 1 << tables_sorted[0][1]) + (1 << log_n_cycles)
        + sum(table_cols(n) << h for n, h in tables_sorted)
    )
    total_gkr_n_vars = log2_ceil_usize(total_active_len)

    quotient, point_gkr, claim_num, claim_den = verify_gkr_quotient(state, total_gkr_n_vars)
    if quotient != EF.zero():
        raise ProofError("logup: GKR sum != 0")

    num, den = EF.zero(), EF.zero()
    def pref_at(offset: int, log_height: int) -> EF:
        n_missing = total_gkr_n_vars - log_height
        bits = to_big_endian_in_field(offset >> log_height, n_missing)
        return eq_poly_outside(bits, point_gkr[:n_missing])

    # Memory section: subtracts the accumulator from `num`, adds (c − fp) to `den`.
    mem_pt   = from_end(point_gkr, log_memory)
    pref     = pref_at(0, log_memory)
    value_memory_acc = state.next_extension_scalar()
    value_memory     = state.next_extension_scalar()
    fp_mem = finger_print(dom_mem, [value_memory, mle_of_01234567_etc(mem_pt)], alphas_eq_poly)
    num = num - pref * value_memory_acc
    den = den + pref * (c - fp_mem)
    offset = 1 << log_memory

    # Bytecode section: same shape; the bytecode MLE is evaluated at the
    # `bytecode_and_acc_point + last log_instr coords of alphas` point and
    # corrected by `Π (1 − alpha_i)` over the bus-data prefix.
    log_byte_pad = max(log_bytecode, tables_sorted[0][1])
    byte_pt      = from_end(point_gkr, log_bytecode)
    pref         = pref_at(offset, log_bytecode)
    pref_pad     = pref_at(offset, log_byte_pad)
    value_bytecode_acc = state.next_extension_scalar()
    bytecode_value = eval_mle_base_at_ef(
        bytecode_multilinear, list(byte_pt) + list(from_end(alphas, log_instr))
    )
    correction = EF.one()
    for a in alphas[: len(alphas) - log_instr]:
        correction = correction * (EF.one() - a)
    fp_byte = (
        bytecode_value * correction
        + mle_of_01234567_etc(byte_pt) * alphas_eq_poly[n_instr_cols]
        + alphas_eq_poly[-1] * EF.from_base(dom_byte)
    )
    num = num - pref * value_bytecode_acc
    den = den + pref * (c - fp_byte) + pref_pad * mle_of_zeros_then_ones(1 << log_bytecode, from_end(point_gkr, log_byte_pad))
    offset += 1 << log_byte_pad

    # Per-table sections: execution-only bytecode lookup, bus column, then
    # one (index, value-array) lookup per `meta.lookups`. Each contributes
    # `pref` to `num` and `pref · (c − fingerprint)` to `den`.
    bus_num_vals: dict[str, EF] = {}
    bus_den_vals: dict[str, EF] = {}
    columns_values: dict[str, dict[int, EF]] = {}
    for name, log_n_rows in tables_sorted:
        meta = tables[name]
        table_values: dict[int, EF] = {}

        if name == "execution":
            eval_on_pc = state.next_extension_scalar()
            instr_evals = state.next_extension_scalars_vec(n_instr_cols)
            table_values[col_pc] = eval_on_pc
            table_values.update({n_runtime_cols + i: e for i, e in enumerate(instr_evals)})
            pref = pref_at(offset, log_n_rows)
            fp = finger_print(dom_byte, list(instr_evals) + [eval_on_pc], alphas_eq_poly)
            num = num + pref
            den = den + pref * (c - fp)
            offset += 1 << log_n_rows

        # Bus column (data flow between tables).
        eval_on_selector = state.next_extension_scalar()
        eval_on_data     = state.next_extension_scalar()
        pref = pref_at(offset, log_n_rows)
        num = num + pref * eval_on_selector
        den = den + pref * eval_on_data
        bus_num_vals[name] = eval_on_selector
        bus_den_vals[name] = eval_on_data
        offset += 1 << log_n_rows

        # Lookups into memory.
        for index_col, value_cols in meta.lookups:
            index_eval = state.next_extension_scalar()
            assert index_col not in table_values
            table_values[index_col] = index_eval
            for i, col_index in enumerate(value_cols):
                value_eval = state.next_extension_scalar()
                assert col_index not in table_values
                table_values[col_index] = value_eval
                pref = pref_at(offset, log_n_rows)
                fp = finger_print(dom_mem, [value_eval, index_eval + EF.from_base(Fp(i))], alphas_eq_poly)
                num = num + pref
                den = den + pref * (c - fp)
                offset += 1 << log_n_rows

        columns_values[name] = table_values

    # Padding tail (zeros over the [offset .. 2^total_gkr_n_vars) region).
    den = den + mle_of_zeros_then_ones(offset, point_gkr)
    if num != claim_num: raise ProofError("logup: numerators value mismatch")
    if den != claim_den: raise ProofError("logup: denominators value mismatch")

    return GenericLogupStatements(
        memory_and_acc_point=list(mem_pt),
        value_memory=value_memory,
        value_memory_acc=value_memory_acc,
        bytecode_and_acc_point=list(byte_pt),
        value_bytecode_acc=value_bytecode_acc,
        bus_numerators_values=bus_num_vals,
        bus_denominators_values=bus_den_vals,
        gkr_point=list(point_gkr),
        columns_values=columns_values,
    )





# ─── Pluggable per-table AIR constraint evaluator ──────────────────────────────────────────────────────────


class ConstraintFolder:
    """Each `assert_zero(x)` contributes `alpha_powers[i] · x` to the
    running accumulator. `assert_eq` and `assert_bool` are sugar."""

    def __init__(self, up: Sequence[EF], down: Sequence[EF], alpha_powers: Sequence[EF]) -> None:
        self.up, self.down, self.alpha_powers = list(up), list(down), list(alpha_powers)
        self.accumulator: EF = EF.zero()
        self.i = 0

    def assert_zero(self, x: EF) -> None:
        self.accumulator = self.accumulator + self.alpha_powers[self.i] * x
        self.i += 1

    def assert_eq(self, x: EF, y: EF) -> None:
        self.assert_zero(x - y)

    def assert_bool(self, x: EF) -> None:
        # bool_check(x) = x · (1 − x), zero iff x ∈ {0, 1}.
        self.assert_zero(x * (EF.one() - x))


def _eval_virtual_bus_column(extra_data: dict, flag: EF, data: Sequence[EF]) -> EF:
    """`(Σ αᵢ · dataᵢ + α_last · LOGUP_PRECOMPILE_DOMAINSEP) · bus_beta + flag`."""
    alphas: list[EF] = extra_data["logup_alphas_eq_poly"]
    bus_beta: EF = extra_data["bus_beta"]
    assert len(data) < len(alphas)
    inner = EF.zero()
    for a, d in zip(alphas, data):
        inner = inner + a * d
    inner = inner + alphas[-1] * EF.from_base(Fp(1))  # LOGUP_PRECOMPILE_DOMAINSEP = 1
    return inner * bus_beta + flag


def air_constraint_eval(
    table: TableMeta,
    col_evals: Sequence[EF],
    alpha_powers: Sequence[EF],
    extra_data: dict,
) -> EF:
    """Evaluate `table`'s AIR constraint polynomial at the given column evals.

    `col_evals[:n_columns]` is the `up` row, `col_evals[n_columns:]` is the
    `down` row (only present for tables with `down_column_indexes`).
    """
    folder = ConstraintFolder(col_evals[:table.n_columns], col_evals[table.n_columns:], alpha_powers)
    {
        "execution": _eval_air_execution,
        "extension_op": _eval_air_extension_op,
        "poseidon16_compress": _eval_air_poseidon16,
    }[table.name](folder, table, extra_data)
    return folder.accumulator



# ─── Execution-table AIR (lean_vm/src/tables/execution/air.rs) ──────────────────────────────────────────────────────────


def _eval_air_execution(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    # Column layout (execution/air.rs): pc, fp, addr_{a,b,c}, value_{a,b,c},
    # operand_{a,b,c}, flag_{a,b,c}, flag_c_fp, flag_ab_fp, mul, jump, aux,
    # precompile_data. `down[0..2]` carries the next row's (pc, fp).
    (pc, fp, addr_a, addr_b, addr_c, value_a, value_b, value_c,
     operand_a, operand_b, operand_c, flag_a, flag_b, flag_c, flag_c_fp,
     flag_ab_fp, mul, jump, aux, precompile_data) = folder.up[:20]
    next_pc, next_fp = folder.down[0], folder.down[1]
    one = EF.one()

    # `nu_x = flag · operand + (1 − flag − flag_ab_fp) · value + flag_ab_fp · (fp + operand)`.
    nfa = -(flag_a + flag_ab_fp - one)
    nfb = -(flag_b + flag_ab_fp - one)
    nfc = -(flag_c + flag_c_fp - one)
    nu_a = flag_a * operand_a + nfa * value_a + flag_ab_fp * (fp + operand_a)
    nu_b = flag_b * operand_b + nfb * value_b + flag_ab_fp * (fp + operand_b)
    nu_c = flag_c * operand_c + nfc * value_c + flag_c_fp * (fp + operand_c)

    # `aux` is a 2-bit gadget: aux=0→nothing, aux=1→add, aux=2→deref. From it
    # we derive boolean flags (`add` / `deref`) and the precompile catch-all.
    add   = aux * EF.from_base(Fp(2)) - aux * aux
    deref = aux * (aux - one) * EF.from_base(_INV_TWO)
    is_precompile = -(add + mul + deref + jump - one)

    # Constraint 1: precompile bus column.
    folder.assert_zero(_eval_virtual_bus_column(
        extra_data, is_precompile, [precompile_data, nu_a, nu_b, nu_c],
    ))
    # Constraints 2-4: address consistency on memory operands.
    folder.assert_zero(nfa * (addr_a - (fp + operand_a)))
    folder.assert_zero(nfb * (addr_b - (fp + operand_b)))
    folder.assert_zero(nfc * (addr_c - (fp + operand_c)))
    # Constraints 5-6: add / mul gates.
    folder.assert_zero(add * (nu_b - (nu_a + nu_c)))
    folder.assert_zero(mul * (nu_b - nu_a * nu_c))
    # Constraints 7-8: deref — `addr_b == value_a + operand_b` and `value_b == nu_c`.
    folder.assert_zero(deref * (addr_b - (value_a + operand_b)))
    folder.assert_zero(deref * (value_b - nu_c))
    # Constraints 9-13: jump control flow.
    jc = jump * nu_a
    folder.assert_zero(jc * (nu_a - one))
    folder.assert_zero(jc * (next_pc - nu_b))
    folder.assert_zero(jc * (next_fp - nu_c))
    not_jc = -(jc - one)
    folder.assert_zero(not_jc * (next_pc - (pc + one)))
    folder.assert_zero(not_jc * (next_fp - fp))



# ─── Extension-op-table AIR (lean_vm/src/tables/extension_op/air.rs) ──────────────────────────────────────────────────────────


# Bus-data magic numbers from extension_op/air.rs (precompile-data layout).
_EXT_OP_FLAG_IS_BE = 4
_EXT_OP_FLAG_ADD = 8
_EXT_OP_FLAG_MUL = 16
_EXT_OP_FLAG_POLY_EQ = 32
_EXT_OP_LEN_MULTIPLIER = 64


def _quintic_mul_ef(a: Sequence[EF], b: Sequence[EF]) -> list[EF]:
    """Port of `quintic_mul` from `koalabear/quintic_extension/extension.rs` —
    multiplication of 5-tuples of EF as quintic-extension elements."""
    assert len(a) == 5 and len(b) == 5
    b0m3, b1m4, b4m2 = b[0] - b[3], b[1] - b[4], b[4] - b[2]
    rows = [
        [b[0], b[4], b[3], b[2], b1m4],
        [b[1], b[0], b[4], b[3], b[2]],
        [b[2], b1m4, b0m3, b4m2, b[3] - b1m4],
        [b[3], b[2], b1m4, b0m3, b4m2],
        [b[4], b[3], b[2], b1m4, b0m3],
    ]
    def dot(row: list[EF]) -> EF:
        acc = a[0] * row[0]
        for i in range(1, 5):
            acc = acc + a[i] * row[i]
        return acc
    return [dot(row) for row in rows]


def _eval_air_extension_op(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    # `up`: is_be, start, flag_{add,mul,poly_eq}, len, idx_{a,b,res}, then four
    # 5-EF blocks va, vb, vres, comp. `down`: start, is_be, len, flag_*, idx_*,
    # comp[0..5] (we only use the next-row `start` and `comp` here).
    is_be, start, flag_add, flag_mul, flag_poly_eq, len_col, idx_a, idx_b, idx_res = folder.up[:9]
    va, vb, vres, comp = (folder.up[9 + 5 * k : 9 + 5 * (k + 1)] for k in range(4))
    # `down`: start, is_be, len, flag_{add,mul,poly_eq}, idx_{a,b}, comp[0..5].
    (start_down, is_be_down, len_down, flag_add_down, flag_mul_down,
     flag_poly_eq_down, idx_a_down, idx_b_down) = folder.down[:8]
    comp_down = folder.down[8:13]
    one = EF.one()

    # Constraint 1: precompile bus.
    aux = (is_be * EF.from_base(Fp(_EXT_OP_FLAG_IS_BE))
           + flag_add * EF.from_base(Fp(_EXT_OP_FLAG_ADD))
           + flag_mul * EF.from_base(Fp(_EXT_OP_FLAG_MUL))
           + flag_poly_eq * EF.from_base(Fp(_EXT_OP_FLAG_POLY_EQ))
           + len_col * EF.from_base(Fp(_EXT_OP_LEN_MULTIPLIER)))
    folder.assert_zero(_eval_virtual_bus_column(
        extra_data, start * (flag_add + flag_mul + flag_poly_eq), [aux, idx_a, idx_b, idx_res],
    ))

    # Constraints 2-6: bool flags.
    for f in (is_be, start, flag_add, flag_mul, flag_poly_eq):
        folder.assert_bool(f)

    # `va` is `Fp` when in base-extension mode, full EF otherwise; `comp_tail`
    # carries the next chunk's comp when this row isn't a `start`.
    is_ee, not_start_down = -(is_be - one), -(start_down - one)
    va_f_or_ef  = [va[0]] + [va[k] * is_ee for k in range(1, 5)]
    comp_tail   = [comp_down[k] * not_start_down for k in range(5)]
    va_times_vb = _quintic_mul_ef(va_f_or_ef, vb)

    # Constraints 7-11: add.
    for k in range(5):
        folder.assert_zero((comp[k] - (va_f_or_ef[k] + vb[k] + comp_tail[k])) * flag_add)
    # Constraints 12-16: mul.
    for k in range(5):
        folder.assert_zero((comp[k] - (va_times_vb[k] + comp_tail[k])) * flag_mul)

    # Constraints 17-21: poly_eq gate — `comp ← (2·va·vb − va − vb + 1) · comp_down_or_one`.
    poly_eq_val = [va_times_vb[k] + va_times_vb[k] - va_f_or_ef[k] - vb[k] + (one if k == 0 else EF.zero()) for k in range(5)]
    comp_down_or_one = [comp_down[0] * not_start_down + start_down] + [comp_down[k] * not_start_down for k in range(1, 5)]
    poly_eq_result = _quintic_mul_ef(poly_eq_val, comp_down_or_one)
    for k in range(5):
        folder.assert_zero((comp[k] - poly_eq_result[k]) * flag_poly_eq)

    # Constraints 22-26: result matches `comp` when `start`.
    for k in range(5):
        folder.assert_zero((comp[k] - vres[k]) * start)

    # Constraints 27-31: down-row consistency on non-start rows
    folder.assert_zero(not_start_down * (len_col - len_down - one))
    folder.assert_zero(not_start_down * (is_be - is_be_down))
    folder.assert_zero(not_start_down * (flag_add - flag_add_down))
    folder.assert_zero(not_start_down * (flag_mul - flag_mul_down))
    folder.assert_zero(not_start_down * (flag_poly_eq - flag_poly_eq_down))

    # Constraint 32-33: idx_a / idx_b increment
    a_increment = is_be + is_ee * EF.from_base(Fp(5))  # DIMENSION = 5
    folder.assert_zero(not_start_down * (idx_a_down - idx_a - a_increment))
    folder.assert_zero(not_start_down * (idx_b_down - idx_b - EF.from_base(Fp(5))))

    # Constraint 34: start_down enforces len=1
    folder.assert_zero(start_down * (len_col - one))



# ─── Poseidon16-compress AIR (lean_vm/src/tables/poseidon_16/mod.rs) ──────────────────────────────────────────────────────────


@functools.cache
def _p1c() -> dict:
    """Poseidon1 round constants + matrices, lifted from the Rust-dumped JSON."""
    import json
    from pathlib import Path
    raw = json.loads(Path(__file__).with_name("poseidon1_constants.json").read_text())
    fp_mat = lambda m: [[Fp(v) for v in row] for row in m]
    fp_vec = lambda v: [Fp(x) for x in v]
    return {
        "half_full_rounds":  raw["half_full_rounds"],
        "partial_rounds":    raw["partial_rounds"],
        "initial_constants": fp_mat(raw["initial_constants"]),
        "final_constants":   fp_mat(raw["final_constants"]),
        "sparse_m_i":        fp_mat(raw["sparse_m_i"]),
        "sparse_first_row":  fp_mat(raw["sparse_first_row"]),
        "sparse_v":          fp_mat(raw["sparse_v"]),
        "sparse_first_rc":   fp_vec(raw["sparse_first_round_constants"]),
        "sparse_scalar_rc":  fp_vec(raw["sparse_scalar_round_constants"]),
        "mds_dense":         fp_mat(raw["mds_dense"]),
    }


_POSEIDON_WIDTH = 16
_HALF_DIGEST_LEN = 4
_POSEIDON_HALF_OUTPUT_SHIFT             = 1 << 1
_POSEIDON_HARDCODED_LEFT_4_FLAG_SHIFT   = 1 << 2
_POSEIDON_HARDCODED_LEFT_4_OFFSET_SHIFT = 1 << 3


def _matvec_kb(mat: list[list[Fp]], state: list[EF]) -> list[EF]:
    """`mat × state` — base-field matrix times EF-vector."""
    out: list[EF] = []
    for row in mat:
        acc = EF.zero()
        for s, m in zip(state, row):
            acc = acc + s * m
        out.append(acc)
    return out


def _full_round(state: list[EF], rc1: list[Fp], rc2: list[Fp]) -> list[EF]:
    """Two MDS-sandwiched cubic S-boxes — one "full round" pair."""
    for rc in (rc1, rc2):
        state = _matvec_kb(_p1c()["mds_dense"], [(s + EF.from_base(c)) * (s + EF.from_base(c)) * (s + EF.from_base(c)) for s, c in zip(state, rc)])
    return state


def _eval_poseidon1_16(folder: ConstraintFolder, cols: dict, extra_data: dict) -> None:
    """Evaluate the Poseidon1-16 permutation as AIR constraints. Each "post"
    column commits an intermediate state; we assert local computation matches,
    then *adopt* the committed value to bound polynomial degree."""
    const = _p1c()
    state = list(cols["inputs"])
    initial = list(cols["inputs"])  # used for Davies-Meyer at the end

    # Initial full rounds (HALF_INITIAL_FULL_ROUNDS = 2 pairs each).
    half_initial = const["half_full_rounds"] // 2
    for r in range(half_initial):
        state = _full_round(state, const["initial_constants"][2 * r], const["initial_constants"][2 * r + 1])
        for i, post in enumerate(cols["beginning_full_rounds"][r]):
            folder.assert_eq(state[i], post)
            state[i] = post

    # Transition into partial rounds (uses sparse `m_i`, no constraints).
    state = [s + EF.from_base(c) for s, c in zip(state, const["sparse_first_rc"])]
    state = _matvec_kb(const["sparse_m_i"], state)

    # Partial rounds: S-box on `state[0]` only, then sparse linear layer.
    n_partial = const["partial_rounds"]
    for r in range(n_partial):
        cubed = state[0] * state[0] * state[0]
        folder.assert_eq(cubed, cols["partial_rounds"][r])
        state[0] = cols["partial_rounds"][r]
        if r < n_partial - 1:
            state[0] = state[0] + const["sparse_scalar_rc"][r]
        old_s0 = state[0]
        # new_s0 = ⟨first_row[r], state⟩ ;  state[i] += old_s0 · v[r][i-1].
        new_s0 = EF.zero()
        for j in range(_POSEIDON_WIDTH):
            new_s0 = new_s0 + state[j] * const["sparse_first_row"][r][j]
        state[0] = new_s0
        for i in range(1, _POSEIDON_WIDTH):
            state[i] = state[i] + old_s0 * const["sparse_v"][r][i - 1]

    # Ending full rounds except the very last pair.
    half_final = const["half_full_rounds"] // 2
    for r in range(half_final - 1):
        state = _full_round(state, const["final_constants"][2 * r], const["final_constants"][2 * r + 1])
        for i, post in enumerate(cols["ending_full_rounds"][r]):
            folder.assert_eq(state[i], post)
            state[i] = post

    # Last full round + Davies-Meyer: state += initial_state, then compare to
    # outputs (always for the first half; gated by `flag_half_output` after).
    last = 2 * (half_final - 1)
    state = _full_round(state, const["final_constants"][last], const["final_constants"][last + 1])
    state = [s + init for s, init in zip(state, initial)]
    one_minus_half = EF.one() - cols["flag_half_output"]
    for idx in range(_POSEIDON_WIDTH // 2):
        if idx < _HALF_DIGEST_LEN:
            folder.assert_eq(state[idx], cols["outputs"][idx])
        else:
            folder.assert_zero(one_minus_half * (state[idx] - cols["outputs"][idx]))


def _eval_air_poseidon16(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    const = _p1c()
    up = folder.up
    one = EF.one()
    W = _POSEIDON_WIDTH
    half_initial = const["half_full_rounds"] // 2
    half_final   = const["half_full_rounds"] // 2

    # Decode the Poseidon1Cols16 layout by sequential slicing.
    o = 0
    def take(n: int) -> list[EF]:
        nonlocal o
        chunk, o = up[o : o + n], o + n
        return list(chunk)

    [flag_active, index_b, index_res, flag_half_output, flag_hardcoded_left,
     offset_hardcoded_left, effective_index_left_first, effective_index_left_second] = take(8)
    inputs                = take(W)
    beginning_full_rounds = [take(W) for _ in range(half_initial)]
    partial_cols          = take(const["partial_rounds"])
    ending_full_rounds    = [take(W) for _ in range(half_final - 1)]
    outputs               = take(W // 2)

    # Reconstruct `precompile_data` from the flags + offset.
    precompile_data = (
        one
        + flag_half_output      * EF.from_base(Fp(_POSEIDON_HALF_OUTPUT_SHIFT))
        + flag_hardcoded_left   * EF.from_base(Fp(_POSEIDON_HARDCODED_LEFT_4_FLAG_SHIFT))
        + flag_hardcoded_left * offset_hardcoded_left * EF.from_base(Fp(_POSEIDON_HARDCODED_LEFT_4_OFFSET_SHIFT))
    )
    not_hcl = one - flag_hardcoded_left
    index_a = effective_index_left_second - not_hcl * EF.from_base(Fp(_HALF_DIGEST_LEN))

    # Constraint 1: bus column.
    folder.assert_zero(_eval_virtual_bus_column(
        extra_data, flag_active, [precompile_data, index_a, index_b, index_res],
    ))
    # Constraints 2-4: bool flags.
    for f in (flag_active, flag_half_output, flag_hardcoded_left):
        folder.assert_bool(f)
    # Constraints 5-6: hardcoded-left consistency.
    folder.assert_zero(flag_hardcoded_left * (offset_hardcoded_left - effective_index_left_first))
    folder.assert_zero(not_hcl * (index_a - effective_index_left_first))

    _eval_poseidon1_16(folder, {
        "inputs": inputs,
        "beginning_full_rounds": beginning_full_rounds,
        "partial_rounds": partial_cols,
        "ending_full_rounds": ending_full_rounds,
        "outputs": outputs,
        "flag_half_output": flag_half_output,
    }, extra_data)



# ─── AIR-stage orchestration in verify_execution ──────────────────────────────────────────────────────────


# Per-table compile-time spec (Rust: `<Table as Air>::{degree_air, n_constraints,
# down_column_indexes}`). The down-column lists for `execution` and
# `extension_op` are exactly what their `Air::down_column_indexes` returns.
_TABLE_SPECS: dict[str, dict] = {
    "execution":           {"degree": 5,  "n_constraints": 13, "down": [0, 1]},
    "extension_op":        {"degree": 4,  "n_constraints": 16, "down": [1, 0, 5, 2, 3, 4, 6, 7, 24, 25, 26, 27, 28]},
    "poseidon16_compress": {"degree": 10, "n_constraints": 81, "down": []},
}


def _powers(x: EF, n: int) -> list[EF]:
    """`[1, x, x², …, x^(n−1)]`."""
    out, cur = [], EF.one()
    for _ in range(n):
        out.append(cur)
        cur = cur * x
    return out


def verify_air_stage(
    state: VerifierState,
    logup: GenericLogupStatements,
    logup_c: EF,
    logup_alphas_eq_poly: list[EF],
    table_log_heights: dict[str, int],
    tables: dict[str, TableMeta],
    public_input: Sequence[Fp],
    log_memory: int,
) -> tuple[dict[str, list[tuple[list[EF], dict[int, EF], dict[int, EF]]]], list[EF], EF]:
    """Returns `(committed_statements, public_memory_random_point, public_memory_eval)`.
    `committed_statements[name]` is a list of `(point, eq_values, next_values)`
    triples — one per session for that table."""
    bus_beta, air_alpha, eta = state.sample(), state.sample(), state.sample()
    alpha_powers = _powers(air_alpha, max(_TABLE_SPECS[n]["n_constraints"] for n in tables) + 1)
    tables_sorted = sort_tables_by_height(table_log_heights)
    eta_powers = _powers(eta, len(tables_sorted))
    extra_data = {"logup_alphas_eq_poly": logup_alphas_eq_poly, "bus_beta": bus_beta, "c": logup_c}

    # Initial AIR sum: Σ η^t · (bus_num · sign + β · (bus_den − c)).
    initial_sum = EF.zero()
    for (name, _), eta_pow in zip(tables_sorted, eta_powers):
        sign = -EF.one() if tables[name].bus_direction == "Pull" else EF.one()
        bus_value = logup.bus_numerators_values[name] * sign + bus_beta * (logup.bus_denominators_values[name] - logup_c)
        initial_sum = initial_sum + eta_pow * bus_value

    max_degree_plus_one = max(_TABLE_SPECS[n]["degree"] + 1 for n, _ in tables_sorted)
    n_max = tables_sorted[0][1]
    sc = verify_sumcheck(state, initial_sum, n_max, max_degree_plus_one)

    # Per-table: read col_evals, evaluate the AIR constraint, accumulate, build claims.
    # Each table's committed statements start with its logup eq-values entry.
    committed = {
        name: [(list(from_end(logup.gkr_point, table_log_heights[name])),
                dict(logup.columns_values[name]), {})]
        for name in tables
    }
    my_air_final_value = EF.zero()
    for (name, log_n_rows), eta_pow in zip(tables_sorted, eta_powers):
        meta, down = tables[name], _TABLE_SPECS[name]["down"]
        col_evals = state.next_extension_scalars_vec(meta.n_columns + len(down))
        constraint_eval = air_constraint_eval(meta, col_evals, alpha_powers, extra_data)

        # Per-table contribution = η^t · (Π unused-prefix coords) · eq · C(col_evals).
        natural_pt = list(reversed(sc.point[-log_n_rows:])) if log_n_rows else []
        k_t = EF.one()
        for x in sc.point[: n_max - log_n_rows]:
            k_t = k_t * x
        bus_point = from_end(logup.gkr_point, log_n_rows)
        my_air_final_value = my_air_final_value + eta_pow * k_t * eq_poly_outside(bus_point, natural_pt) * constraint_eval

        eq_values = {i: col_evals[i] for i in range(meta.n_columns)}
        next_values = {idx: col_evals[meta.n_columns + j] for j, idx in enumerate(down)}
        committed[name].append((natural_pt, eq_values, next_values))

    if my_air_final_value != sc.value:
        raise ProofError("AIR sumcheck: my_air_final_value != claimed_air_final_value")

    # Public memory MLE evaluation at a fresh random point.
    public_memory = padd_with_zero_to_next_power_of_two(public_input)
    pm_point = state.sample_vec(log2_strict_usize(len(public_memory)))
    pm_eval = eval_multilinear_evals([EF.from_base(f) for f in public_memory], pm_point)
    return committed, list(pm_point), pm_eval



# ─── Top-level verifier ──────────────────────────────────────────────────────────


def verify_execution(
    bytecode: Bytecode,
    public_input: Sequence[Fp],
    proof: Proof,
    tables: Sequence[TableMeta],
    constants: dict,
    bytecode_multilinear: list[int],
) -> dict:
    """Verify a leanVM execution proof. Port of `verify_execution.rs`.

    Flow: observe prologue → read dims → parse stacked-PCS WHIR commitment →
    generic logup → AIR sumcheck → assemble global WHIR statements → final WHIR.
    `tables` must be in canonical Rust order (`ALL_TABLES`)."""
    state = VerifierState(proof)
    state.observe_scalars(list(public_input))
    state.observe_scalars(poseidon16_compress(bytecode.hash, SNARK_DOMAIN_SEP))

    # Dimensions: log_inv_rate, log_memory, public_input_len, then per-table log_n_rows.
    dims = [int(x.value) for x in state.next_base_scalars_vec(3 + len(tables))]
    log_inv_rate, log_memory, public_input_len, *table_log_n_rows = dims

    if public_input_len != len(public_input):
        raise ProofError("InvalidProof: public_input length mismatch")
    if not MIN_WHIR_LOG_INV_RATE <= log_inv_rate <= MAX_WHIR_LOG_INV_RATE:
        raise ProofError("InvalidRate")
    if any(h < MIN_LOG_N_ROWS_PER_TABLE for h in table_log_n_rows):
        raise ProofError("InvalidProof: table too small")
    if log_memory < max(max(table_log_n_rows, default=0), bytecode.log_size):
        raise ProofError("InvalidProof: memory smaller than tables/bytecode")
    if not MIN_LOG_MEMORY_SIZE <= log_memory <= MAX_LOG_MEMORY_SIZE:
        raise ProofError("InvalidProof: log_memory out of range")
    if bytecode.log_size < MIN_BYTECODE_LOG_SIZE:
        raise ProofError("InvalidProof: bytecode too small")

    table_log_heights = {t.name: h for t, h in zip(tables, table_log_n_rows)}
    table_n_columns   = {t.name: t.n_columns for t in tables}
    tables_by_name    = {t.name: t for t in tables}

    parsed_commitment = stacked_pcs_parse_commitment(
        state, log_inv_rate, log_memory, bytecode.log_size, table_log_heights, table_n_columns,
    )

    # Logup phase.
    logup_c = state.sample()
    max_bus_width = 1 + max(constants["max_precompile_bus_width"], constants["n_instruction_columns"])
    logup_alphas = state.sample_vec(log2_ceil_usize(max_bus_width))
    logup_alphas_eq = eval_eq(logup_alphas)
    logup = verify_generic_logup(
        state, logup_c, logup_alphas, logup_alphas_eq, log_memory, bytecode_multilinear,
        table_log_heights, tables_by_name, constants,
    )

    # AIR phase.
    committed, pm_point, pm_eval = verify_air_stage(
        state, logup, logup_c, logup_alphas_eq,
        table_log_heights, tables_by_name, public_input, log_memory,
    )

    # WHIR finale: seed previous_statements with memory, public-memory, bytecode-acc.
    stacked_n_vars = parsed_commitment.num_variables
    mk = lambda point, values: SparseStatement(stacked_n_vars, list(point), values)
    previous = [
        mk(logup.memory_and_acc_point, [
            SparseValue(0, logup.value_memory),
            SparseValue(1, logup.value_memory_acc),
        ]),
        mk(pm_point, [SparseValue(0, pm_eval)]),
        mk(logup.bytecode_and_acc_point, [SparseValue(
            (2 << log_memory) >> bytecode.log_size, logup.value_bytecode_acc,
        )]),
    ]
    global_statements = stacked_pcs_global_statements(
        stacked_n_vars, log_memory, bytecode.log_size, previous,
        table_log_heights, committed, tables_by_name, constants,
    )
    whir_verify(state, whir_config(log_inv_rate, stacked_n_vars), parsed_commitment, global_statements)

    return {"log_inv_rate": log_inv_rate, "log_memory": log_memory, "stacked_n_vars": stacked_n_vars}



# ─── Test vector loader + entry point ──────────────────────────────────────────────────────────


def poseidon_compress_slice_iv(data: Sequence[Fp]) -> list[Fp]:
    """Hash a multiple-of-8 sequence with Poseidon16/Davies-Meyer, seeded by
    an all-zero IV — matches `utils::poseidon_compress_slice(.., use_iv=true)`."""
    assert data and len(data) % 8 == 0
    h = [Fp(0)] * 8
    for i in range(0, len(data), 8):
        h = poseidon16_compress(h, list(data[i : i + 8]))
    return h


def main() -> int:
    """Load the end-to-end test vector and run `verify_execution`."""
    import array, json
    from pathlib import Path

    vector_path = Path(__file__).resolve().parents[2] / "target" / "zkvm_test_vectors" / "proof.json"
    if not vector_path.exists():
        print(f"Test vector not found at {vector_path}. Generate it first with:\n"
              "    cargo test --release -p lean_prover --test dump_zkvm_vector -- --nocapture")
        return 1

    print(f"Loading {vector_path.name}...")
    raw = json.loads(vector_path.read_text())

    # Bytecode multilinear (raw u32 LE sidecar).
    arr = array.array("I"); arr.frombytes((vector_path.parent / raw["bytecode_multilinear_path"]).read_bytes())
    assert len(arr) == raw["bytecode_multilinear_len"]
    bytecode_multilinear: list[int] = list(arr)

    fp_list = lambda xs: [Fp(v) for v in xs]
    bytecode     = Bytecode(fp_list(raw["bytecode_hash"]), raw["bytecode_log_size"])
    public_input = fp_list(raw["public_input"])
    input_data   = fp_list(raw["input_data"])
    proof = Proof(
        transcript=fp_list(raw["proof"]["transcript"]),
        merkle_openings=[
            MerkleOpening(leaf_data=fp_list(o["leaf_data"]), path=[fp_list(d) for d in o["path"]])
            for o in raw["proof"]["merkle_openings"]
        ],
    )

    # Sanity: re-derive `public_input` from `input_data` to check the hash.
    if poseidon_compress_slice_iv(input_data) != public_input:
        print("FAIL: poseidon_compress_slice(input_data) doesn't match dumped public_input")
        return 1

    try:
        result = verify_execution(
            bytecode, public_input, proof,
            tables_from_json(raw["tables"]), raw["constants"], bytecode_multilinear,
        )
    except ProofError as e:
        print(f"FAIL: {e}")
        return 1

    print(f"OK: rec-aggregation proof verified ({result})")
    return 0


if __name__ == "__main__":
    import sys as _sys
    _sys.exit(main())
