"""Pure-Python verifier for leanVM execution proofs.

Single end-to-end test vector — a rec-aggregation proof over one XMSS
signature — is generated by the Rust side and stored under `target/`.
Run this script to verify it.

Setup (one-time):
    # Python venv + lean_spec (gives us KoalaBear `Fp` and the Poseidon1
    # permutation).
    uv venv .venv --python 3.12
    VIRTUAL_ENV=.venv uv pip install "git+https://github.com/leanEthereum/leanSpec.git"

    # Rust-side data (hardcoded soundness numbers + Poseidon round constants).
    cargo test --release -p lean_prover --test dump_whir_configs        -- --nocapture
    cargo test --release -p lean_prover --test dump_poseidon1_constants -- --nocapture

    # The end-to-end test vector (~17 MiB; takes a minute or two).
    cargo test --release -p lean_prover --test dump_zkvm_vector         -- --nocapture

Run:
    .venv/bin/python crates/lean_prover/verifier.py
"""

from __future__ import annotations

import functools
from dataclasses import dataclass, field
from typing import Sequence

from lean_spec.subspecs.koalabear import Fp, P
from lean_spec.subspecs.poseidon1 import PARAMS_16, Poseidon1

# WHIR builder constants (lean_prover/src/lib.rs).
WHIR_INITIAL_FOLDING_FACTOR = 7
WHIR_SUBSEQUENT_FOLDING_FACTOR = 5
MAX_NUM_VARIABLES_TO_SEND_COEFFS = 8
RS_DOMAIN_INITIAL_REDUCTION_FACTOR = 5

# Poseidon16 sponge parameters. The challenger uses the compression-with-
# domain-separator design: `state` is a RATE-sized buffer; `observe(chunk)`
# does `state ← permute(state || chunk)[:RATE]`; sampling re-permutes the
# state with a per-call domain separator.
RATE = 8
WIDTH = 16
CAPACITY = WIDTH - RATE
DIGEST_ELEMS = 8

# leanVM SNARK domain separator (lean_prover/src/lib.rs).
SNARK_DOMAIN_SEP = [
    Fp(v) for v in (
        130704175, 1303721200, 493664240, 1035493700,
        2063844858, 1410214009, 1938905908, 1696767928,
    )
]

# Bounds (lean_vm/src/core/constants.rs).
MIN_WHIR_LOG_INV_RATE, MAX_WHIR_LOG_INV_RATE = 1, 4
MIN_LOG_MEMORY_SIZE, MAX_LOG_MEMORY_SIZE = 16, 26
MIN_LOG_N_ROWS_PER_TABLE = 8
MIN_BYTECODE_LOG_SIZE = 8
BASE_TWO_ADICITY = 24  # KoalaBear

# WHIR config table dumped by `cargo test -p lean_prover --test dump_whir_configs`.
# Lives next to this file.
WHIR_CONFIGS_PATH = "whir_configs.json"



# ─── Error type ──────────────────────────────────────────────────────────


class ProofError(Exception):
    """Mirrors backend::ProofError."""



# Quintic extension field: EF = Fp[X] / (X^5 + X^2 - 1)
# Reduction rule: X^5 = 1 - X^2.



class EF:
    """Element of the degree-5 extension of KoalaBear.

    Stored as 5 base coefficients `c[0..5]` representing `c0 + c1 X + ... + c4 X^4`.
    Irreducible polynomial: X^5 + X^2 - 1, i.e. X^5 ≡ 1 - X^2.
    """

    __slots__ = ("c",)
    DIMENSION = 5

    def __init__(self, coeffs: Sequence[Fp]):
        assert len(coeffs) == 5
        self.c = tuple(coeffs)

    # --- constructors -----------------------------------------------------

    @staticmethod
    def zero() -> "EF":
        return EF([Fp(0)] * 5)

    @staticmethod
    def one() -> "EF":
        return EF([Fp(1), Fp(0), Fp(0), Fp(0), Fp(0)])

    @staticmethod
    def from_base(x: Fp) -> "EF":
        return EF([x, Fp(0), Fp(0), Fp(0), Fp(0)])

    @staticmethod
    def from_basis_coefficients(coeffs: Sequence[Fp]) -> "EF":
        return EF(coeffs)

    # --- arithmetic -------------------------------------------------------

    def __add__(self, other) -> "EF":
        if isinstance(other, Fp):
            return EF([self.c[0] + other, *self.c[1:]])
        return EF([a + b for a, b in zip(self.c, other.c)])

    __radd__ = __add__

    def __sub__(self, other) -> "EF":
        if isinstance(other, Fp):
            return EF([self.c[0] - other, *self.c[1:]])
        return EF([a - b for a, b in zip(self.c, other.c)])

    def __rsub__(self, other) -> "EF":
        # other - self, where other is Fp
        return EF([other - self.c[0], *[-c for c in self.c[1:]]])

    def __neg__(self) -> "EF":
        return EF([-a for a in self.c])

    def __mul__(self, other: "EF | Fp | int") -> "EF":
        if isinstance(other, Fp):
            return EF([a * other for a in self.c])
        if isinstance(other, int):
            f = Fp(other % P)
            return EF([a * f for a in self.c])
        # Schoolbook poly mul mod (X^5 + X^2 - 1).
        a, b = self.c, other.c
        prod = [Fp(0)] * 9  # degree up to 8
        for i in range(5):
            for j in range(5):
                prod[i + j] = prod[i + j] + a[i] * b[j]
        # Reduce: X^5 = 1 - X^2,  X^k for k >= 5 reduced repeatedly.
        for k in range(8, 4, -1):  # 8,7,6,5
            coef = prod[k]
            if int(coef.value) == 0:
                continue
            # X^k = X^(k-5) * X^5 = X^(k-5) * (1 - X^2)
            prod[k] = Fp(0)
            prod[k - 5] = prod[k - 5] + coef
            prod[k - 3] = prod[k - 3] - coef
        return EF(prod[:5])

    __rmul__ = __mul__

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, EF):
            return NotImplemented
        return self.c == other.c

    def __hash__(self) -> int:
        return hash(self.c)

    def __repr__(self) -> str:
        return f"EF({[int(x.value) for x in self.c]})"

    def is_zero(self) -> bool:
        return all(int(x.value) == 0 for x in self.c)

    def inv(self) -> "EF":
        """Inverse via Fermat: a^(q-2) where q = P^5. Slow but simple."""
        if self.is_zero():
            raise ZeroDivisionError("EF inverse of zero")
        exp = P ** 5 - 2
        return self.pow(exp)

    def pow(self, n: int) -> "EF":
        if n < 0:
            return self.inv().pow(-n)
        result = EF.one()
        base = self
        while n > 0:
            if n & 1:
                result = result * base
            base = base * base
            n >>= 1
        return result



# ─── Poseidon16-based Challenger ──────────────────────────────────────────────────────────


_POSEIDON16 = Poseidon1(PARAMS_16)


def poseidon16_compress_in_place(state: list[Fp]) -> list[Fp]:
    """Davies-Meyer compression: `permute(state) + state` (length WIDTH)."""
    assert len(state) == WIDTH
    return [a + b for a, b in zip(_POSEIDON16.permute(state), state)]


def poseidon16_compress(left: Sequence[Fp], right: Sequence[Fp]) -> list[Fp]:
    """2:1 Merkle compression: top DIGEST_ELEMS of `compress_in_place(left || right)`."""
    assert len(left) == DIGEST_ELEMS and len(right) == DIGEST_ELEMS
    return poseidon16_compress_in_place(list(left) + list(right))[:DIGEST_ELEMS]


def hash_slice(data: Sequence[Fp]) -> list[Fp]:
    """`symetric::hash_slice` with WIDTH=16, RATE=OUT=8 (right-to-left absorbing)."""
    assert len(data) % RATE == 0
    n_chunks = len(data) // RATE
    assert n_chunks >= 2
    state = list(data[len(data) - WIDTH :])
    state = poseidon16_compress_in_place(state)
    for chunk_idx in range(n_chunks - 3, -1, -1):
        offset = chunk_idx * RATE
        state = state[:CAPACITY] + list(data[offset : offset + RATE])
        state = poseidon16_compress_in_place(state)
    return state[:DIGEST_ELEMS]


class Challenger:
    """Poseidon16 challenger (old "compression + domain-separator" design).

    Mirrors `fiat_shamir::challenger` on this branch:
      - `state` is a length-RATE buffer (8 elements).
      - `observe(value)`: `state = permute(state || value)[:RATE]`.
      - `sample_many(n)`: hash `(domain_sep_i || state)` for `i ∈ 0..=n`;
        return the first `n`, advance `state` to the last one.
    """

    def __init__(self) -> None:
        self.state: list[Fp] = [Fp(0)] * RATE

    def observe(self, value: Sequence[Fp]) -> None:
        assert len(value) == RATE
        out = poseidon16_compress_in_place(list(self.state) + list(value))
        self.state = out[:RATE]

    def observe_many(self, scalars: Sequence[Fp]) -> None:
        for i in range(0, len(scalars), RATE):
            chunk = list(scalars[i : i + RATE])
            if len(chunk) < RATE:
                chunk = chunk + [Fp(0)] * (RATE - len(chunk))
            self.observe(chunk)

    # Alias matching `Challenger::observe_scalars` on this branch.
    observe_scalars = observe_many

    def sample_many(self, n: int) -> list[list[Fp]]:
        sampled: list[list[Fp]] = []
        last: list[Fp] | None = None
        for i in range(n + 1):
            domain_sep = [Fp(i)] + [Fp(0)] * (RATE - 1)
            hashed = poseidon16_compress_in_place(domain_sep + list(self.state))[:RATE]
            if i < n:
                sampled.append(hashed)
            else:
                last = hashed
        if last is not None:
            self.state = last
        return sampled

    def sample_ef_vec(self, n: int) -> list[EF]:
        """Mirrors utils::sample_vec — pulls ceil(n*5/8) blocks, takes first n*5."""
        n_blocks = (n * EF.DIMENSION + RATE - 1) // RATE
        flat: list[Fp] = []
        for block in self.sample_many(n_blocks):
            flat.extend(block)
        flat = flat[: n * EF.DIMENSION]
        return [EF(flat[i : i + EF.DIMENSION]) for i in range(0, len(flat), EF.DIMENSION)]

    def sample_ef(self) -> EF:
        return self.sample_ef_vec(1)[0]

    def sample_in_range(self, bits: int, n_samples: int) -> list[int]:
        """Mirrors challenger::sample_in_range — not perfectly uniform."""
        assert bits < 31
        n_blocks = (n_samples + RATE - 1) // RATE
        flat: list[Fp] = []
        for block in self.sample_many(n_blocks):
            flat.extend(block)
        mask = (1 << bits) - 1
        return [int(x.value) & mask for x in flat[:n_samples]]



# ─── Proof container + VerifierState (transcript reader) ──────────────────────────────────────────────────────────


@dataclass
class MerkleOpening:
    """Restored Merkle opening: matches fiat_shamir::transcript::MerkleOpening."""

    leaf_data: list[Fp]
    path: list[list[Fp]]  # each sibling is a length-DIGEST_ELEMS digest


@dataclass
class Proof:
    """Verifier-side raw proof: matches backend::RawProof.

    `transcript` is the flat RAW transcript (every absorbed group padded to a
    multiple of RATE with zeros — the format the zkDSL recursion verifier reads).
    `merkle_openings` is the list of already-restored openings in the order the
    verifier consumes them (no pruning machinery on the Python side).
    """

    transcript: list[Fp]
    merkle_openings: list[MerkleOpening] = field(default_factory=list)


def _next_multiple_of(n: int, m: int) -> int:
    return ((n + m - 1) // m) * m


class VerifierState:
    """Drives the Fiat-Shamir transcript: reads scalars from `proof.transcript`,
    samples challenges from the challenger, and yields restored Merkle openings.

    Every read pads to RATE (the zkDSL recursion format) — `n` real scalars are
    consumed as `next_multiple_of(n, RATE)` raw scalars, the trailing positions
    must be zero, and the full RATE-aligned chunk is what the challenger absorbs.
    """

    def __init__(self, proof: Proof) -> None:
        self.challenger = Challenger()
        self.transcript = list(proof.transcript)
        self.merkle_openings = list(proof.merkle_openings)
        self.offset = 0
        self.merkle_opening_index = 0

    def _read_padded(self, n: int) -> list[Fp]:
        """Read `next_multiple_of(n, RATE)` raw scalars, assert the trailing
        positions are zero, observe the full padded chunk, return all of it."""
        n_padded = _next_multiple_of(n, RATE)
        if self.offset + n_padded > len(self.transcript):
            raise ProofError("ExceededTranscript")
        chunk = self.transcript[self.offset : self.offset + n_padded]
        self.offset += n_padded
        for i in range(n, n_padded):
            if int(chunk[i].value) != 0:
                raise ProofError("InvalidTranscript: non-zero padding")
        self.challenger.observe_many(chunk)
        return chunk

    def observe_scalars(self, scalars: Sequence[Fp]) -> None:
        self.challenger.observe_many(list(scalars))

    def next_base_scalars_vec(self, n: int) -> list[Fp]:
        return self._read_padded(n)[:n]

    def next_extension_scalars_vec(self, n: int) -> list[EF]:
        flat = self.next_base_scalars_vec(n * EF.DIMENSION)
        return [EF(flat[i : i + EF.DIMENSION]) for i in range(0, len(flat), EF.DIMENSION)]

    def next_extension_scalar(self) -> EF:
        return self.next_extension_scalars_vec(1)[0]

    def sample(self) -> EF:
        return self.challenger.sample_ef()

    def sample_vec(self, n: int) -> list[EF]:
        return self.challenger.sample_ef_vec(n)

    def sample_in_range(self, bits: int, n_samples: int) -> list[int]:
        return self.challenger.sample_in_range(bits, n_samples)

    def next_merkle_opening(self) -> MerkleOpening:
        if self.merkle_opening_index >= len(self.merkle_openings):
            raise ProofError("ExceededTranscript: no more Merkle openings")
        self.merkle_opening_index += 1
        return self.merkle_openings[self.merkle_opening_index - 1]

    def check_pow_grinding(self, bits: int) -> None:
        """Grinding witness is written as `[witness, 0, 0, 0, 0, 0, 0, 0]`."""
        if bits == 0:
            return
        chunk = self._read_padded(1)
        if int(self.challenger.state[0].value) & ((1 << bits) - 1) != 0:
            raise ProofError("InvalidGrindingWitness")



# ─── Small helpers (Bytecode metadata, EF utilities, log2, padding) ──────────────────────────────────────────────


@dataclass
class Bytecode:
    """What `verify_execution` needs about a bytecode program."""
    hash: list[Fp]
    log_size: int


# Multiplicative inverse of 2 in Fp (KoalaBear). Used to halve EF elements.
_INV_TWO = Fp(pow(2, P - 2, P))


def log2_ceil_usize(x: int) -> int:
    return 0 if x <= 1 else (x - 1).bit_length()


def log2_strict_usize(x: int) -> int:
    assert x > 0 and (x & (x - 1)) == 0, f"{x} is not a power of two"
    return x.bit_length() - 1


def padd_with_zero_to_next_power_of_two(values: Sequence[Fp]) -> list[Fp]:
    if not values:
        return [Fp(0)]
    n = 1 << log2_ceil_usize(len(values))
    return list(values) + [Fp(0)] * (n - len(values))


# ─── Merkle path verify ──────────────────────────────────


def merkle_verify_path(
    commit: list[Fp],
    log_height: int,
    index: int,
    opened_values: Sequence[Fp],
    opening_proof: Sequence[list[Fp]],
) -> bool:
    """Hash the leaf, walk up `log_height` siblings, compare to the commitment."""
    if len(opening_proof) != log_height:
        return False
    cur = hash_slice(list(opened_values))
    for sibling in opening_proof:
        cur = poseidon16_compress(cur, sibling) if index & 1 == 0 else poseidon16_compress(sibling, cur)
        index >>= 1
    return list(commit) == list(cur)



# ─── WHIR polynomial primitives (poly + whir crates) ──────────────────────────────────────────────────────────


def expand_from_univariate(x: EF, num_variables: int) -> list[EF]:
    """[x, x^2, x^4, ..., x^{2^{n-1}}] — matches MultilinearPoint::expand_from_univariate."""
    out: list[EF] = []
    cur = x
    for _ in range(num_variables):
        out.append(cur)
        cur = cur * cur
    return out


def eq_poly_outside(a: Sequence[EF], b: Sequence[EF]) -> EF:
    """Π (1 + 2 a_i b_i − a_i − b_i)  (eq polynomial)."""
    assert len(a) == len(b)
    one = EF.one()
    acc = one
    for x, y in zip(a, b):
        acc = acc * (one + (x * y) + (x * y) - x - y)
    return acc


def next_mle(x: Sequence[EF], y: Sequence[EF]) -> EF:
    assert len(x) == len(y)
    n = len(x)
    one = EF.one()
    eq_prefix: list[EF] = [one]
    for i in range(n):
        eq_i = x[i] * y[i] + (one - x[i]) * (one - y[i])
        eq_prefix.append(eq_prefix[i] * eq_i)
    low_suffix: list[EF] = [one] * (n + 1)
    for i in range(n - 1, -1, -1):
        low_suffix[i] = low_suffix[i + 1] * x[i] * (one - y[i])
    s = EF.zero()
    for arr in range(n):
        carry = (one - x[arr]) * y[arr]
        s = s + eq_prefix[arr] * carry * low_suffix[arr + 1]
    prod = one
    for v in list(x) + list(y):
        prod = prod * v
    return s + prod


def eval_multilinear_evals(evals: Sequence[EF], point: Sequence[EF]) -> EF:
    """Evaluate a multilinear in *evaluation* form (length 2^n) at point ∈ EF^n.

    Big-endian indexing: index `i` corresponds to the bits `(b_0, ..., b_{n-1})`
    where `b_0` is the *most significant* bit, matching `poly::eval_multilinear`.
    Fold variables from the last to the first.
    """
    assert len(evals) == 1 << len(point)
    cur = list(evals)
    for r in reversed(point):
        nxt: list[EF] = []
        for j in range(0, len(cur), 2):
            nxt.append(cur[j] + (cur[j + 1] - cur[j]) * r)
        cur = nxt
    return cur[0]


def eval_multilinear_coeffs(coeffs: Sequence[EF], point: Sequence[EF]) -> EF:
    """poly::eval_multilinear_coeffs: split coeffs in half, recurse.

    `coeffs` represents `Σ_b c_b · x_0^{b_0} · ... · x_{n-1}^{b_{n-1}}`
    in the standard multilinear coefficient basis.
    """
    assert len(coeffs) == 1 << len(point)
    if not point:
        return coeffs[0]
    x = point[0]
    tail = point[1:]
    half = len(coeffs) // 2
    return eval_multilinear_coeffs(coeffs[:half], tail) + eval_multilinear_coeffs(coeffs[half:], tail) * x


@dataclass
class SparseValue:
    selector: int
    value: EF


@dataclass
class SparseStatement:

    total_num_variables: int
    point: list[EF]  # the "inner" point, length = inner_num_variables
    values: list[SparseValue]
    is_next: bool = False

    @property
    def inner_num_variables(self) -> int:
        return len(self.point)

    @property
    def selector_num_variables(self) -> int:
        return self.total_num_variables - self.inner_num_variables

    @staticmethod
    def dense(point: list[EF], value: EF) -> "SparseStatement":
        return SparseStatement(len(point), point, [SparseValue(0, value)])

    @staticmethod
    def unique_value(total: int, index: int, value: EF) -> "SparseStatement":
        return SparseStatement(total, [], [SparseValue(index, value)])

    @staticmethod
    def new_next(total: int, point: list[EF], values: list[SparseValue]) -> "SparseStatement":
        return SparseStatement(total, point, values, is_next=True)



# ─── WHIR config helpers: derive integer-only parameters from the trimmed JSON ──────────────────────────────────────────────────────────


def whir_n_rounds_and_final_sumcheck(num_variables: int) -> tuple[int, int]:
    """FoldingFactor::compute_number_of_rounds with default (7, 5, max_send=8)."""
    nv_except_first = num_variables - WHIR_INITIAL_FOLDING_FACTOR
    max_send = MAX_NUM_VARIABLES_TO_SEND_COEFFS
    if nv_except_first < max_send:
        return 0, nv_except_first
    n_rounds = -(-(nv_except_first - max_send) // WHIR_SUBSEQUENT_FOLDING_FACTOR)
    final_sumcheck_rounds = nv_except_first - n_rounds * WHIR_SUBSEQUENT_FOLDING_FACTOR
    return n_rounds, final_sumcheck_rounds


def whir_folding_factor_at_round(r: int) -> int:
    return WHIR_INITIAL_FOLDING_FACTOR if r == 0 else WHIR_SUBSEQUENT_FOLDING_FACTOR


def whir_rs_reduction_factor(r: int) -> int:
    return RS_DOMAIN_INITIAL_REDUCTION_FACTOR if r == 0 else 1


def whir_log_inv_rate_at(starting_log_inv_rate: int, round_index: int) -> int:
    rate = starting_log_inv_rate
    for r in range(round_index):
        rate += whir_folding_factor_at_round(r) - whir_rs_reduction_factor(r)
    return rate


# KoalaBear two-adic generators: index `bits` is the primitive 2^bits-th root
# of unity (canonical-form u32 values, mirrors `TWO_ADIC_GENERATORS`).
KB_TWO_ADIC_GENERATORS: list[int] = [
    0x1, 0x7F000000, 0x7E010002, 0x6832FE4A, 0x08DBD69C, 0x0A28F031, 0x5C4A5B99,
    0x29B75A80, 0x17668B8A, 0x27AD539B, 0x334D48C7, 0x7744959C, 0x768FC6FA,
    0x303964B2, 0x3E687D4D, 0x45A60E61, 0x6E2F4D7A, 0x163BD499, 0x6C4A8A45,
    0x143EF899, 0x514DDCAD, 0x484EF19B, 0x205D63C3, 0x68E7DD49, 0x6AC49F88,
]


def two_adic_generator(bits: int) -> Fp:
    assert 0 <= bits <= BASE_TWO_ADICITY
    return Fp(KB_TWO_ADIC_GENERATORS[bits])


def whir_domain_size_at(num_variables: int, starting_log_inv_rate: int, round_index: int) -> int:
    """domain_size that goes into `round_parameters[round_index]`.

    The Rust code seeds `domain_size = 1 << (num_variables + log_inv_rate)` and
    halves by `rs_reduction_factor(round)` BEFORE moving to the next round, so
    the value stored in round r is the *current* domain_size pre-reduction.
    """
    domain_log = num_variables + starting_log_inv_rate
    for r in range(round_index):
        domain_log -= whir_rs_reduction_factor(r)
    return 1 << domain_log


# The Rust-dumped JSON only carries the float-derived numbers (query counts,
# OOD samples, grinding bits); every other parameter is integer arithmetic
# we recompute on the fly via the helpers above.


@dataclass(frozen=True)
class WhirRoundConfig:
    num_queries: int
    ood_samples: int
    query_pow_bits: int
    folding_pow_bits: int


@dataclass(frozen=True)
class WhirConfig:
    log_inv_rate: int
    num_variables: int
    commitment_ood_samples: int
    starting_folding_pow_bits: int
    final_queries: int
    final_query_pow_bits: int
    rounds: tuple[WhirRoundConfig, ...]


@functools.cache
def _whir_configs() -> dict[tuple[int, int], WhirConfig]:
    import json
    from pathlib import Path
    raw = json.loads(Path(__file__).with_name(WHIR_CONFIGS_PATH).read_text())
    return {
        (c["log_inv_rate"], c["num_variables"]): WhirConfig(
            **{k: c[k] for k in WhirConfig.__annotations__ if k != "rounds"},
            rounds=tuple(WhirRoundConfig(**r) for r in c["rounds"]),
        )
        for c in raw
    }


def whir_config(log_inv_rate: int, num_variables: int) -> WhirConfig:
    try:
        return _whir_configs()[(log_inv_rate, num_variables)]
    except KeyError:
        raise KeyError(
            f"No WHIR config for (log_inv_rate={log_inv_rate}, num_variables={num_variables}). "
            "Regenerate with: cargo test -p lean_prover --test dump_whir_configs"
        ) from None



# ─── WHIR verifier (port of crates/whir/src/verify.rs) ──────────────────────────────────────────────────────────


@dataclass
class ParsedCommitment:

    num_variables: int
    root: list[Fp]              # length DIGEST_ELEMS
    ood_points: list[EF]
    ood_answers: list[EF]

    def oods_constraints(self) -> list[SparseStatement]:
        """One dense SparseStatement per (point, eval) pair."""
        out: list[SparseStatement] = []
        for p, ev in zip(self.ood_points, self.ood_answers):
            point = expand_from_univariate(p, self.num_variables)
            out.append(SparseStatement.dense(point, ev))
        return out


def parsed_commitment_parse(state: VerifierState, num_variables: int, ood_samples: int) -> ParsedCommitment:
    root = state.next_base_scalars_vec(DIGEST_ELEMS)
    ood_points: list[EF] = []
    ood_answers: list[EF] = []
    if ood_samples > 0:
        ood_points = state.sample_vec(ood_samples)
        ood_answers = state.next_extension_scalars_vec(ood_samples)
    return ParsedCommitment(
        num_variables=num_variables,
        root=root,
        ood_points=ood_points,
        ood_answers=ood_answers,
    )


def _check_sumcheck_identity(coeffs: list[EF], target: EF) -> None:
    """`h(0) + h(1) = target`, i.e. `coeffs[0] + sum(coeffs) == target`."""
    s = coeffs[0]
    for c in coeffs:
        s = s + c
    if s != target:
        raise ProofError("Sumcheck identity failed: h(0) + h(1) != target")


def _eval_univariate(coeffs: list[EF], x: EF) -> EF:
    """Horner: c[0] + c[1]*x + c[2]*x^2 + ..."""
    acc = EF.zero()
    for c in reversed(coeffs):
        acc = acc * x + c
    return acc


def verify_sumcheck_rounds(
    state: VerifierState,
    claimed_sum_ref: list[EF],   # 1-element box, mutated in-place
    rounds: int,
    pow_bits: int,
) -> list[EF]:
    """Degree-2 sumcheck (3 coeffs per round). Returns the folding randomness
    and mutates `claimed_sum_ref[0]` to the final claim."""
    randomness: list[EF] = []
    for _ in range(rounds):
        coeffs = state.next_extension_scalars_vec(3)
        _check_sumcheck_identity(coeffs, claimed_sum_ref[0])
        state.check_pow_grinding(pow_bits)
        r = state.sample()
        claimed_sum_ref[0] = _eval_univariate(coeffs, r)
        randomness.append(r)
    return randomness


def combine_constraints(
    state: VerifierState,
    claimed_sum_ref: list[EF],
    constraints: list[SparseStatement],
) -> list[EF]:
    gamma: EF = state.sample()
    combination = [EF.one()]
    for smt in constraints:
        for v in smt.values:
            pow_prev = combination[-1]
            claimed_sum_ref[0] = claimed_sum_ref[0] + pow_prev * v.value
            combination.append(pow_prev * gamma)
    combination.pop()
    return combination


def verify_stir_challenges(
    state: VerifierState,
    cfg: WhirConfig,
    round_index: int,
    num_variables: int,
    log_inv_rate: int,
    folding_factor: int,
    next_folding_factor: int,
    num_queries: int,
    query_pow_bits: int,
    commitment: ParsedCommitment,
    folding_randomness: list[EF],
) -> list[SparseStatement]:
    """`folding_factor` is the folding factor applied AT this round (i.e. how the
    leaves are arranged). `next_folding_factor` is the AIR sumcheck folding for
    the *next* hop; for the final pseudo-round it equals `folding_factor`.

    Returns STIR constraints (SparseStatements) for the next claim-combining.
    """
    # Domain size at this round (pre-RS-reduction for round `round_index`).
    domain_size = whir_domain_size_at(cfg.num_variables, cfg.log_inv_rate, round_index)
    folded_domain_size = domain_size >> folding_factor
    folded_domain_gen = two_adic_generator(domain_size.bit_length() - 1 - folding_factor)

    state.check_pow_grinding(query_pow_bits)
    indices = state.sample_in_range(folded_domain_size.bit_length() - 1, num_queries)

    leafs_base_field = round_index == 0
    log_height = folded_domain_size.bit_length() - 1
    answers_ef: list[list[EF]] = []
    for idx in indices:
        op = state.next_merkle_opening()
        if not merkle_verify_path(commitment.root, log_height, idx, op.leaf_data, op.path):
            raise ProofError("Merkle verification failed")
        # leaf_data is base; if leafs encode EF, pack 5 base → 1 EF.
        if leafs_base_field:
            answers_ef.append([EF.from_base(f) for f in op.leaf_data])
        else:
            ans: list[EF] = []
            for i in range(0, len(op.leaf_data), EF.DIMENSION):
                ans.append(EF(op.leaf_data[i : i + EF.DIMENSION]))
            answers_ef.append(ans)

    # Each answer is a length-(2^folding_factor) eval-form multilinear; fold at folding_randomness.
    folds: list[EF] = [eval_multilinear_evals(a, folding_randomness) for a in answers_ef]

    stir_constraints: list[SparseStatement] = []
    for idx, fold in zip(indices, folds):
        point = folded_domain_gen.value
        # point = folded_domain_gen ^ idx, as a base-field element wrapped into EF.
        gen_pow = pow(int(folded_domain_gen.value), idx, P)
        ef_pt = EF.from_base(Fp(gen_pow))
        expanded = expand_from_univariate(ef_pt, num_variables)
        stir_constraints.append(SparseStatement.dense(expanded, fold))
    return stir_constraints


def verify_constraint_coeffs(constraint: SparseStatement, coeffs: list[EF]) -> bool:
    """Checks that the constraint's point is `[α, α^2, α^4, ...]` and that
    the univariate polynomial (Horner) evaluates to each claimed value.
    """
    assert constraint.selector_num_variables == 0
    alpha = constraint.point[0]
    for a, b in zip(constraint.point, constraint.point[1:]):
        if a * a != b:
            return False
    # Horner from highest-degree coefficient (last in `coeffs`) downward.
    univ_eval = EF.zero()
    for c in reversed(coeffs):
        univ_eval = univ_eval * alpha + c
    return all(univ_eval == v.value for v in constraint.values)


def eval_constraints_poly(
    constraints: list[tuple[list[EF], list[SparseStatement]]],
    point: list[EF],
) -> EF:
    """`constraints` is a list of (combination_randomness, sparse_statements) per
    round. `point` is the global folding randomness; it is sliced down by the
    folding factor of each preceding round before use.
    """
    value = EF.zero()
    pt = list(point)
    for round_idx, (randomness, smts) in enumerate(constraints):
        if round_idx > 0:
            k = whir_folding_factor_at_round(round_idx - 1)
            pt = pt[k:]
        i = 0
        for smt in smts:
            inner_pt = pt[len(pt) - smt.inner_num_variables :]
            if smt.is_next:
                common_weight = next_mle(smt.point, inner_pt)
            else:
                common_weight = eq_poly_outside(smt.point, inner_pt)
            for v in smt.values:
                # Per-selector lagrange weight on bits NOT covered by the inner point.
                lagrange = EF.one()
                for j in range(smt.selector_num_variables):
                    bit = (v.selector >> (smt.selector_num_variables - 1 - j)) & 1
                    lagrange = lagrange * (pt[j] if bit else (EF.one() - pt[j]))
                value = value + lagrange * common_weight * randomness[i]
                i += 1
        assert i == len(randomness)
    return value


def whir_verify(
    state: VerifierState,
    cfg: WhirConfig,
    parsed_commitment: ParsedCommitment,
    statement: list[SparseStatement],
) -> list[EF]:
    for s in statement:
        assert s.total_num_variables == parsed_commitment.num_variables

    n_rounds, final_sumcheck_rounds = whir_n_rounds_and_final_sumcheck(cfg.num_variables)

    round_constraints: list[tuple[list[EF], list[SparseStatement]]] = []
    round_folding: list[list[EF]] = []
    claimed_sum_ref: list[EF] = [EF.zero()]
    prev_commitment = parsed_commitment

    # OODS + initial statement combine.
    initial_constraints = prev_commitment.oods_constraints() + statement
    combo = combine_constraints(state, claimed_sum_ref, initial_constraints)
    round_constraints.append((combo, initial_constraints))

    # Initial sumcheck.
    folding_rand = verify_sumcheck_rounds(
        state,
        claimed_sum_ref,
        whir_folding_factor_at_round(0),
        cfg.starting_folding_pow_bits,
    )
    round_folding.append(folding_rand)

    # Round loop.
    for r in range(n_rounds):
        rp = cfg.rounds[r]
        # New num_variables = num_variables_at_round(after this round's first absorb)
        # In Rust: round_state.num_variables = num_variables - folding_factor.total_number(r+1)
        nvars_round = cfg.num_variables - sum(
            whir_folding_factor_at_round(i) for i in range(r + 1)
        )
        new_commitment = parsed_commitment_parse(state, nvars_round, rp.ood_samples)

        stir_constraints = verify_stir_challenges(
            state,
            cfg,
            round_index=r,
            num_variables=nvars_round,
            log_inv_rate=whir_log_inv_rate_at(cfg.log_inv_rate, r),
            folding_factor=whir_folding_factor_at_round(r),
            next_folding_factor=whir_folding_factor_at_round(r + 1),
            num_queries=rp.num_queries,
            query_pow_bits=rp.query_pow_bits,
            commitment=prev_commitment,
            folding_randomness=round_folding[-1],
        )
        constraints_r = new_commitment.oods_constraints() + stir_constraints
        combo_r = combine_constraints(state, claimed_sum_ref, constraints_r)
        round_constraints.append((combo_r, constraints_r))

        folding_rand_r = verify_sumcheck_rounds(
            state,
            claimed_sum_ref,
            whir_folding_factor_at_round(r + 1),
            rp.folding_pow_bits,
        )
        round_folding.append(folding_rand_r)
        prev_commitment = new_commitment

    # Final round: read the final polynomial in coefficient form, then run a
    # last batch of STIR queries against the last commitment.
    n_vars_final = cfg.num_variables - sum(
        whir_folding_factor_at_round(i) for i in range(n_rounds + 1)
    )
    final_coeffs = state.next_extension_scalars_vec(1 << n_vars_final)

    final_domain_size = whir_domain_size_at(cfg.num_variables, cfg.log_inv_rate, n_rounds)
    final_folding_factor = whir_folding_factor_at_round(n_rounds)
    folded_domain_size_final = final_domain_size >> final_folding_factor
    folded_gen_final = two_adic_generator(final_domain_size.bit_length() - 1 - final_folding_factor)
    log_height_final = folded_domain_size_final.bit_length() - 1

    state.check_pow_grinding(cfg.final_query_pow_bits)
    indices_final = state.sample_in_range(log_height_final, cfg.final_queries)
    final_stir: list[SparseStatement] = []
    for idx in indices_final:
        op = state.next_merkle_opening()
        if not merkle_verify_path(prev_commitment.root, log_height_final, idx, op.leaf_data, op.path):
            raise ProofError("Final Merkle verification failed")
        if n_rounds == 0:
            answers = [EF.from_base(f) for f in op.leaf_data]
        else:
            answers = [EF(op.leaf_data[i : i + EF.DIMENSION]) for i in range(0, len(op.leaf_data), EF.DIMENSION)]
        fold = eval_multilinear_evals(answers, round_folding[-1])
        ef_pt = EF.from_base(Fp(pow(int(folded_gen_final.value), idx, P)))
        final_stir.append(SparseStatement.dense(expand_from_univariate(ef_pt, n_vars_final), fold))

    # Verify STIR constraints directly on final polynomial coefficients.
    for c in final_stir:
        if not verify_constraint_coeffs(c, final_coeffs):
            raise ProofError("Final STIR constraint mismatch")

    # Final sumcheck.
    final_sumcheck_rand = verify_sumcheck_rounds(
        state, claimed_sum_ref, final_sumcheck_rounds, 0
    )
    round_folding.append(final_sumcheck_rand)

    # Flatten all folding randomness; evaluate the constraint weights polynomial.
    folding_randomness_flat = [r for chunk in round_folding for r in chunk]
    eval_weights = eval_constraints_poly(round_constraints, folding_randomness_flat)

    # Final coeffs are evaluated at REVERSED final_sumcheck_rand.
    reversed_point = list(reversed(final_sumcheck_rand))
    final_value = eval_multilinear_coeffs(final_coeffs, reversed_point)
    if claimed_sum_ref[0] != eval_weights * final_value:
        raise ProofError("WHIR final sumcheck check failed")

    return folding_randomness_flat



# ─── Table metadata (mirror of lean_vm::tables::table_trait) ──────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Lookup:
    """A single memory lookup descriptor (`LookupIntoMemory` in Rust)."""

    index: int
    values: tuple[int, ...]


@dataclass(frozen=True)
class TableMeta:
    """The bits of `lean_vm::Table` the verifier actually consumes."""

    name: str
    n_columns: int
    bus_direction: str         # "Pull" or "Push"
    lookups: tuple[Lookup, ...]


def tables_from_json(obj: list[dict]) -> list[TableMeta]:
    return [
        TableMeta(
            name=t["name"],
            n_columns=int(t["n_columns"]),
            bus_direction=t["bus"]["direction"],
            lookups=tuple(
                Lookup(index=int(l["index"]), values=tuple(int(v) for v in l["values"]))
                for l in t["lookups"]
            ),
        )
        for t in obj
    ]



# ─── Stacked PCS — port of sub_protocols/stacked_pcs.rs ──────────────────────────────────────────────────────────


def compute_stacked_n_vars(
    log_memory: int,
    log_bytecode: int,
    table_log_heights: dict[str, int],
    table_n_columns: dict[str, int],
) -> int:
    """The stacked polynomial concatenates:
      - 2 copies of memory               -> 2 * 2^log_memory
      - one bytecode accumulator padded  -> 2^max(log_bytecode, max_table_log_n_rows)
      - per table: n_columns * 2^log_n_rows
    """
    max_table_log_n_rows = max(table_log_heights.values())
    total_len = (2 << log_memory) + (
        1 << max(log_bytecode, max_table_log_n_rows)
    )
    for name, log_n_rows in table_log_heights.items():
        total_len += table_n_columns[name] << log_n_rows
    return log2_ceil_usize(total_len)


def stacked_pcs_global_statements(
    stacked_n_vars: int,
    memory_n_vars: int,
    bytecode_n_vars: int,
    previous_statements: list[SparseStatement],
    table_log_heights: dict[str, int],
    committed_statements: dict[str, list[tuple[list[EF], dict[int, EF], dict[int, EF]]]],
    tables: dict[str, TableMeta],
    constants: dict,
) -> list[SparseStatement]:
    """Stacks the per-table column claims into the global statement list passed to
    `WhirConfig::verify`. Tables are processed in descending-height order.
    """
    assert len(table_log_heights) == len(committed_statements)
    tables_sorted = sort_tables_by_height(table_log_heights)

    out = list(previous_statements)
    offset = 2 << memory_n_vars  # memory + memory_acc
    max_table_n_vars = tables_sorted[0][1]
    offset += 1 << max(bytecode_n_vars, max_table_n_vars)  # bytecode acc

    col_pc = constants["col_pc"]
    starting_pc = constants["starting_pc"]
    ending_pc = constants["ending_pc"]

    for name, n_vars in tables_sorted:
        if name == "execution":
            out.append(
                SparseStatement.unique_value(
                    stacked_n_vars,
                    offset + (col_pc << n_vars),
                    EF.from_base(Fp(starting_pc)),
                )
            )
            out.append(
                SparseStatement.unique_value(
                    stacked_n_vars,
                    offset + ((col_pc + 1) << n_vars) - 1,
                    EF.from_base(Fp(ending_pc)),
                )
            )

        for (point, eq_values, next_values) in committed_statements[name]:
            # Rust uses BTreeMap → ascending-key iteration. Python dicts are
            # insertion-ordered, so we have to sort explicitly here.
            if next_values:
                out.append(
                    SparseStatement.new_next(
                        stacked_n_vars,
                        list(point),
                        [
                            SparseValue((offset >> n_vars) + col_index, value)
                            for col_index, value in sorted(next_values.items())
                        ],
                    )
                )
            out.append(
                SparseStatement(
                    total_num_variables=stacked_n_vars,
                    point=list(point),
                    values=[
                        SparseValue((offset >> n_vars) + col_index, value)
                        for col_index, value in sorted(eq_values.items())
                    ],
                    is_next=False,
                )
            )

        offset += tables[name].n_columns << n_vars

    return out


def stacked_pcs_parse_commitment(
    state: VerifierState,
    log_inv_rate: int,
    log_memory: int,
    log_bytecode: int,
    table_log_heights: dict[str, int],
    table_n_columns: dict[str, int],
    execution_table_name: str = "execution",
) -> ParsedCommitment:
    """- Memory must be at least as wide as the execution table.
    - The execution table must be the tallest table.
    - The stacked-poly size must fit within the WHIR domain bound.
    The actual commitment parsing is then delegated to `parsed_commitment_parse`.
    """
    exec_log = table_log_heights[execution_table_name]
    if log_memory < exec_log or exec_log < max(table_log_heights.values()):
        raise ProofError("InvalidProof: memory or execution table size invariants broken")

    stacked_n_vars = compute_stacked_n_vars(
        log_memory, log_bytecode, table_log_heights, table_n_columns
    )
    # `WhirConfig::new` asserts stacked_n_vars + log_inv_rate - first_round <= F::TWO_ADICITY.
    max_nv = BASE_TWO_ADICITY + WHIR_INITIAL_FOLDING_FACTOR - log_inv_rate
    if stacked_n_vars > max_nv:
        raise ProofError("InvalidProof: stacked_n_vars exceeds WHIR domain bound")

    cfg = whir_config(log_inv_rate, stacked_n_vars)
    return parsed_commitment_parse(state, stacked_n_vars, cfg.commitment_ood_samples)



# ─── Generic sumcheck verifier (port of `backend/sumcheck/src/verify.rs`) ──────────────────────────────────────────────────────────


@dataclass
class Evaluation:
    """Pair (point, value): claim that a multilinear evaluates to `value` at
    `point`. Mirrors `poly::Evaluation`.
    """

    point: list[EF]
    value: EF


def sumcheck_verify(
    state: VerifierState,
    n_vars: int,
    degree: int,
    expected_sum: EF,
) -> Evaluation:
    """Reads `n_vars` round polynomials in standard univariate basis, each with
    `degree + 1` coefficients. Checks `h(0) + h(1) = target` each round, then
    folds in the challenge. Returns the final point + claimed value."""
    target = expected_sum
    challenges: list[EF] = []
    for _ in range(n_vars):
        coeffs = state.next_extension_scalars_vec(degree + 1)
        _check_sumcheck_identity(coeffs, target)
        r = state.sample()
        challenges.append(r)
        target = _eval_univariate(coeffs, r)
    return Evaluation(point=challenges, value=target)


# ---------------------------------------------------------------------------
# GKR-quotient verifier (port of `sub_protocols::quotient_gkr`)
#
# Verifies the protocol `Σ nᵢ/dᵢ` via a layered sumcheck.
# ---------------------------------------------------------------------------


N_VARS_TO_SEND_GKR_COEFFS = 5


def verify_gkr_quotient(
    state: VerifierState,
    n_vars: int,
) -> tuple[EF, list[EF], EF, EF]:
    """`(quotient, gkr_point, claims_num, claims_den)`.
    """
    assert n_vars > N_VARS_TO_SEND_GKR_COEFFS
    send_len = 1 << N_VARS_TO_SEND_GKR_COEFFS

    last_nums = state.next_extension_scalars_vec(send_len)
    last_dens = state.next_extension_scalars_vec(send_len)
    quotient = _quotient_sum(last_nums, last_dens)

    point: list[EF] = state.sample_vec(N_VARS_TO_SEND_GKR_COEFFS)
    claims_num = eval_multilinear_evals(last_nums, point)
    claims_den = eval_multilinear_evals(last_dens, point)

    for i in range(N_VARS_TO_SEND_GKR_COEFFS, n_vars):
        point, claims_num, claims_den = _verify_gkr_quotient_step(
            state, i, point, claims_num, claims_den
        )
    return quotient, point, claims_num, claims_den


def _verify_gkr_quotient_step(
    state: VerifierState,
    n_vars: int,
    point: list[EF],
    claims_num: EF,
    claims_den: EF,
) -> tuple[list[EF], EF, EF]:
    alpha = state.sample()
    expected_sum = claims_num + alpha * claims_den
    postponed = sumcheck_verify(state, n_vars, 3, expected_sum)
    # Rust: postponed.point.0.reverse();
    postponed_point = list(reversed(postponed.point))
    inner_evals = state.next_extension_scalars_vec(4)

    # constraints_eval = α · n_r · d_r + (n_l · d_r + n_r · d_l)
    constraints_eval = (
        alpha * inner_evals[2] * inner_evals[3]
        + (inner_evals[0] * inner_evals[3] + inner_evals[1] * inner_evals[2])
    )

    if postponed.value != eq_poly_outside(point, postponed_point) * constraints_eval:
        raise ProofError("GKR step: postponed value mismatch")

    beta = state.sample()
    one_minus_beta = EF.one() - beta
    next_num = one_minus_beta * inner_evals[0] + beta * inner_evals[1]
    next_den = one_minus_beta * inner_evals[2] + beta * inner_evals[3]
    next_point = postponed_point + [beta]
    return next_point, next_num, next_den


def _quotient_sum(nums: Sequence[EF], dens: Sequence[EF]) -> EF:
    acc = EF.zero()
    for n, d in zip(nums, dens):
        acc = acc + n * d.inv()
    return acc



# ─── Logup helpers (utils + poly) ──────────────────────────────────────────────────────────


def to_big_endian_in_field(value: int, bit_count: int) -> list[EF]:
    """Returns the `bit_count` bits of `value` MSB-first, each as `EF::ZERO`/`EF::ONE`.
    """
    return [EF.one() if (value >> (bit_count - 1 - i)) & 1 else EF.zero() for i in range(bit_count)]


def from_end(seq: Sequence, n: int) -> list:
    """`utils::from_end` — the last `n` elements."""
    if n == 0:
        return []
    return list(seq[len(seq) - n :])


def mle_of_01234567_etc(point: Sequence[EF]) -> EF:
    """Evaluates the multilinear polynomial whose evaluations on `{0,1}^n` are
    `f(i) = i` (with `i` interpreted big-endian), at `point`.
    """
    if not point:
        return EF.zero()
    e = mle_of_01234567_etc(point[1:])
    bit = EF.from_base(Fp(1 << (len(point) - 1)))
    return (EF.one() - point[0]) * e + point[0] * (e + bit)


def mle_of_zeros_then_ones(n_zeros: int, point: Sequence[EF]) -> EF:
    """Evaluates the multilinear of `[0, ..., 0, 1, ..., 1]` (`n_zeros` zeros, then
    `2^len(point) - n_zeros` ones) at `point`.
    """
    n_values = 1 << len(point)
    assert n_zeros <= n_values
    if n_zeros == 0:
        return EF.one()
    if n_zeros == n_values:
        return EF.zero()
    half = n_values >> 1
    if n_zeros < half:
        return (EF.one() - point[0]) * mle_of_zeros_then_ones(n_zeros, point[1:]) + point[0]
    return point[0] * mle_of_zeros_then_ones(n_zeros - half, point[1:])


def finger_print(table: Fp, data: Sequence[EF], alphas_eq_poly: Sequence[EF]) -> EF:
    """Computes `Σᵢ alphas_eq_poly[i] · data[i] + alphas_eq_poly[-1] · table`.
    """
    assert len(alphas_eq_poly) > len(data)
    acc = EF.zero()
    for a, d in zip(alphas_eq_poly, data):
        acc = acc + a * d
    acc = acc + alphas_eq_poly[-1] * EF.from_base(table)
    return acc


def sort_tables_by_height(
    table_log_heights: dict[str, int],
) -> list[tuple[str, int]]:
    """`BTreeMap` ordering (= alphabetical) breaks ties.
    """
    items = sorted(table_log_heights.items())  # alphabetical
    items.sort(key=lambda kv: -kv[1])
    return items


def eval_eq(point: Sequence[EF]) -> list[EF]:
    """Evaluation table of `eq(point, ·)`: the length-`2^n` vector with
    `eq[i] = Πⱼ (point[j] if bitⱼ(i) else 1 - point[j])` for big-endian `i`.
    """
    out = [EF.one()]
    for p in point:
        nxt: list[EF] = []
        for v in out:
            nxt.append(v * (EF.one() - p))
            nxt.append(v * p)
        out = nxt
    return out



# ─── Generic logup verifier — port of sub_protocols/logup.rs::verify_generic_logup ──────────────────────────────────────────────────────────


@dataclass
class GenericLogupStatements:

    memory_and_acc_point: list[EF]
    value_memory: EF
    value_memory_acc: EF
    bytecode_and_acc_point: list[EF]
    value_bytecode_acc: EF
    bus_numerators_values: dict[str, EF]
    bus_denominators_values: dict[str, EF]
    gkr_point: list[EF]
    columns_values: dict[str, dict[int, EF]]
    total_gkr_n_vars: int
    bytecode_evaluation: Evaluation


def _compute_total_active_len_logup(
    log_memory: int,
    log_bytecode: int,
    tables_sorted: list[tuple[str, int]],
    table_lookups: dict[str, list[Lookup]],
    execution_name: str,
) -> int:
    max_table_height = 1 << tables_sorted[0][1]
    log_n_cycles = next(h for n, h in tables_sorted if n == execution_name)

    def offset_for_table(name: str, log_n_rows: int) -> int:
        num_cols = sum(len(l.values) for l in table_lookups[name]) + 1  # +1 for the bus
        return num_cols << log_n_rows

    return (
        (1 << log_memory)
        + max(1 << log_bytecode, max_table_height)
        + (1 << log_n_cycles)
        + sum(offset_for_table(name, h) for name, h in tables_sorted)
    )


def verify_generic_logup(
    state: VerifierState,
    c: EF,
    alphas: list[EF],
    alphas_eq_poly: list[EF],
    log_memory: int,
    bytecode_multilinear: list[Fp],
    table_log_heights: dict[str, int],
    tables: dict[str, TableMeta],
    constants: dict,
    execution_name: str = "execution",
) -> GenericLogupStatements:
    """`bytecode_multilinear` is the flat coefficient vector of length
    `2^(log_bytecode + ceil(log2(N_INSTRUCTION_COLUMNS)))` — what the Rust
    verifier holds as `&bytecode.instructions_multilinear`.

    `alphas` and `alphas_eq_poly` come from sampling `c` and `log2_ceil(max_bus_width)`
    extension-field elements (per the leanVM `verify_execution`).
    """

    n_instr_cols = constants["n_instruction_columns"]
    n_runtime_cols = constants["n_runtime_columns"]
    col_pc = constants["col_pc"]
    dom_mem = constants["logup_memory_domainsep"]
    dom_byte = constants["logup_bytecode_domainsep"]

    tables_sorted = sort_tables_by_height(table_log_heights)
    n_instr_padded = 1 << log2_ceil_usize(n_instr_cols)  # next power of 2
    log_bytecode = log2_strict_usize(len(bytecode_multilinear) // n_instr_padded)

    table_lookups = {name: list(tables[name].lookups) for name in table_log_heights}
    total_active_len = _compute_total_active_len_logup(
        log_memory, log_bytecode, tables_sorted, table_lookups, execution_name
    )
    total_gkr_n_vars = log2_ceil_usize(total_active_len)

    quotient, point_gkr, numerators_value, denominators_value = verify_gkr_quotient(
        state, total_gkr_n_vars
    )

    if quotient != EF.zero():
        raise ProofError("logup: GKR sum != 0")

    retrieved_num = EF.zero()
    retrieved_den = EF.zero()

    def pref_at(offset: int, log_height: int) -> EF:
        n_missing = total_gkr_n_vars - log_height
        bits = to_big_endian_in_field(offset >> log_height, n_missing)
        return eq_poly_outside(bits, point_gkr[:n_missing])

    # ---- Memory section --------------------------------------------------
    memory_and_acc_point = from_end(point_gkr, log_memory)
    pref = pref_at(0, log_memory)

    value_memory_acc = state.next_extension_scalar()
    retrieved_num = retrieved_num - pref * value_memory_acc

    value_memory = state.next_extension_scalar()
    value_index = mle_of_01234567_etc(memory_and_acc_point)
    retrieved_den = retrieved_den + pref * (
        c - finger_print(Fp(dom_mem), [value_memory, value_index], alphas_eq_poly)
    )
    offset = 1 << log_memory

    # ---- Bytecode section ------------------------------------------------
    log_bytecode_padded = max(log_bytecode, tables_sorted[0][1])
    bytecode_and_acc_point = from_end(point_gkr, log_bytecode)
    pref = pref_at(offset, log_bytecode)
    pref_padded = pref_at(offset, log_bytecode_padded)

    value_bytecode_acc = state.next_extension_scalar()
    retrieved_num = retrieved_num - pref * value_bytecode_acc

    bytecode_index_value = mle_of_01234567_etc(bytecode_and_acc_point)
    log_instr = log2_ceil_usize(n_instr_cols)
    bytecode_point = list(bytecode_and_acc_point) + list(from_end(alphas, log_instr))
    bytecode_value = eval_multilinear_evals(
        [EF.from_base(x) for x in bytecode_multilinear], bytecode_point
    )
    # Correction: `(1 - alpha[0]) * (1 - alpha[1]) * ... * (1 - alpha[k-1])`
    # over the alphas BEFORE the last `log_instr` (= the bus-data slot bits).
    correction = EF.one()
    for a in alphas[: len(alphas) - log_instr]:
        correction = correction * (EF.one() - a)
    bytecode_value_corrected = bytecode_value * correction
    retrieved_den = retrieved_den + pref * (
        c
        - (
            bytecode_value_corrected
            + bytecode_index_value * alphas_eq_poly[n_instr_cols]
            + alphas_eq_poly[-1] * EF.from_base(Fp(dom_byte))
        )
    )

    # Padding for bytecode (bytecode_acc shorter than max_table_height).
    retrieved_den = retrieved_den + pref_padded * mle_of_zeros_then_ones(
        1 << log_bytecode, from_end(point_gkr, log_bytecode_padded)
    )
    offset += 1 << log_bytecode_padded

    # ---- Per-table sections ----------------------------------------------
    bus_num_vals: dict[str, EF] = {}
    bus_den_vals: dict[str, EF] = {}
    columns_values: dict[str, dict[int, EF]] = {}

    for name, log_n_rows in tables_sorted:
        meta = tables[name]
        table_values: dict[int, EF] = {}

        if name == execution_name:
            # 0] Bytecode lookup for the execution table.
            eval_on_pc = state.next_extension_scalar()
            table_values[col_pc] = eval_on_pc

            instr_evals = state.next_extension_scalars_vec(n_instr_cols)
            for i, e in enumerate(instr_evals):
                table_values[n_runtime_cols + i] = e

            pref = pref_at(offset, log_n_rows)
            retrieved_num = retrieved_num + pref  # numerator is 1
            retrieved_den = retrieved_den + pref * (
                c
                - finger_print(
                    Fp(dom_byte),
                    list(instr_evals) + [eval_on_pc],
                    alphas_eq_poly,
                )
            )
            offset += 1 << log_n_rows

        # I] Bus (data flow between tables)
        eval_on_selector = state.next_extension_scalar()
        pref = pref_at(offset, log_n_rows)
        retrieved_num = retrieved_num + pref * eval_on_selector

        eval_on_data = state.next_extension_scalar()
        retrieved_den = retrieved_den + pref * eval_on_data

        bus_num_vals[name] = eval_on_selector
        bus_den_vals[name] = eval_on_data
        offset += 1 << log_n_rows

        # II] Lookups into memory
        for lookup in meta.lookups:
            index_eval = state.next_extension_scalar()
            assert lookup.index not in table_values
            table_values[lookup.index] = index_eval

            for i, col_index in enumerate(lookup.values):
                value_eval = state.next_extension_scalar()
                assert col_index not in table_values
                table_values[col_index] = value_eval

                pref = pref_at(offset, log_n_rows)
                retrieved_num = retrieved_num + pref
                retrieved_den = retrieved_den + pref * (
                    c
                    - finger_print(
                        Fp(dom_mem),
                        [value_eval, index_eval + EF.from_base(Fp(i))],
                        alphas_eq_poly,
                    )
                )
                offset += 1 << log_n_rows

        columns_values[name] = table_values

    # Padding tail (xxx..xxx111...1 region beyond `offset`).
    retrieved_den = retrieved_den + mle_of_zeros_then_ones(offset, point_gkr)

    if retrieved_num != numerators_value:
        raise ProofError("logup: numerators value mismatch")
    if retrieved_den != denominators_value:
        raise ProofError("logup: denominators value mismatch")

    return GenericLogupStatements(
        memory_and_acc_point=list(memory_and_acc_point),
        value_memory=value_memory,
        value_memory_acc=value_memory_acc,
        bytecode_and_acc_point=list(bytecode_and_acc_point),
        value_bytecode_acc=value_bytecode_acc,
        bus_numerators_values=bus_num_vals,
        bus_denominators_values=bus_den_vals,
        gkr_point=list(point_gkr),
        columns_values=columns_values,
        total_gkr_n_vars=total_gkr_n_vars,
        bytecode_evaluation=Evaluation(point=bytecode_point, value=bytecode_value),
    )


# ─── AIR sumcheck helpers (port of sub_protocols/air_sumcheck.rs) ──────────────────────────────────────────────────────────


def natural_ordering_point_for_session(
    sumcheck_air_point: Sequence[EF], log_n_rows: int
) -> list[EF]:
    """Takes the last `log_n_rows` coordinates of the AIR sumcheck point and
    reverses them.
    """
    if log_n_rows == 0:
        return []
    return list(reversed(sumcheck_air_point[-log_n_rows:]))


def back_loaded_table_contribution(
    bus_point: Sequence[EF],
    sumcheck_air_point: Sequence[EF],
    natural_ordering_point: Sequence[EF],
    constraint_eval: EF,
    eta_power: EF,
) -> EF:
    """eta^t · (Π i∈[0, n_max - n_t) sumcheck_point[i]) · eq(bus_point, natural_point) · constraint_eval
    """
    n_t = len(bus_point)
    n_max = len(sumcheck_air_point)
    suffix_start = n_max - n_t
    assert len(natural_ordering_point) == n_t
    eq_val = eq_poly_outside(bus_point, natural_ordering_point)
    k_t = EF.one()
    for x in sumcheck_air_point[:suffix_start]:
        k_t = k_t * x
    return eta_power * k_t * eq_val * constraint_eval


def columns_evals_up_and_down(
    n_columns: int,
    down_column_indexes: Sequence[int],
    col_evals: Sequence[EF],
    natural_ordering_point: Sequence[EF],
) -> tuple[list[EF], dict[int, EF], dict[int, EF]]:
    """Mirror of `air_sumcheck::columns_evals_up_and_down`.

    Splits `col_evals` into the per-column evaluation map plus the "next"
    (= `down`) columns. Returns `(point, eq_values, next_values)`.
    """
    n_up = n_columns
    assert len(col_evals) == n_up + len(down_column_indexes)
    eq_values = {i: col_evals[i] for i in range(n_up)}
    next_values = {
        idx: col_evals[n_up + j] for j, idx in enumerate(down_column_indexes)
    }
    return list(natural_ordering_point), eq_values, next_values



# ─── Pluggable per-table AIR constraint evaluator ──────────────────────────────────────────────────────────


class ConstraintFolder:
    """Each `assert_zero(x)` (or `assert_zero_ef`) contributes
    `alpha_powers[constraint_index] · x` to the accumulator.
    """

    def __init__(self, up: Sequence[EF], down: Sequence[EF], alpha_powers: Sequence[EF]) -> None:
        self.up = list(up)
        self.down = list(down)
        self.alpha_powers = list(alpha_powers)
        self.accumulator: EF = EF.zero()
        self.constraint_index = 0

    def assert_zero(self, x: EF) -> None:
        a = self.alpha_powers[self.constraint_index]
        self.accumulator = self.accumulator + a * x
        self.constraint_index += 1

    # `assert_zero_ef` is identical in EF.
    assert_zero_ef = assert_zero

    def assert_eq(self, x: EF, y: EF) -> None:
        self.assert_zero(x - y)

    def assert_bool(self, x: EF) -> None:
        # bool_check(x) = x * (1 - x). Zero iff x is 0 or 1.
        self.assert_zero(x * (EF.one() - x))


def _eval_virtual_bus_column(extra_data: dict, flag: EF, data: Sequence[EF]) -> EF:
    """`(Σ αᵢ · dataᵢ + α_last · LOGUP_PRECOMPILE_DOMAINSEP) · bus_beta + flag`."""
    alphas: list[EF] = extra_data["logup_alphas_eq_poly"]
    bus_beta: EF = extra_data["bus_beta"]
    assert len(data) < len(alphas)
    inner = EF.zero()
    for a, d in zip(alphas, data):
        inner = inner + a * d
    inner = inner + alphas[-1] * EF.from_base(Fp(1))  # LOGUP_PRECOMPILE_DOMAINSEP = 1
    return inner * bus_beta + flag


def air_constraint_eval(
    table: TableMeta,
    col_evals: Sequence[EF],
    alpha_powers: Sequence[EF],
    extra_data: dict,
) -> EF:
    """Evaluate `table`'s AIR constraint polynomial at the given column evals.

    `col_evals[:n_columns]` is the `up` row, `col_evals[n_columns:]` is the
    `down` row (only present for tables with `down_column_indexes`).
    """
    folder = ConstraintFolder(col_evals[:table.n_columns], col_evals[table.n_columns:], alpha_powers)
    {
        "execution": _eval_air_execution,
        "extension_op": _eval_air_extension_op,
        "poseidon16_compress": _eval_air_poseidon16,
    }[table.name](folder, table, extra_data)
    return folder.accumulator



# ─── Execution-table AIR (lean_vm/src/tables/execution/air.rs) ──────────────────────────────────────────────────────────


# Column indexes for the execution table (mirrors execution/air.rs).
_EXEC = {
    "PC": 0, "FP": 1,
    "MEM_ADDRESS_A": 2, "MEM_ADDRESS_B": 3, "MEM_ADDRESS_C": 4,
    "MEM_VALUE_A": 5, "MEM_VALUE_B": 6, "MEM_VALUE_C": 7,
    "OPERAND_A": 8, "OPERAND_B": 9, "OPERAND_C": 10,
    "FLAG_A": 11, "FLAG_B": 12, "FLAG_C": 13, "FLAG_C_FP": 14,
    "FLAG_AB_FP": 15, "MUL": 16, "JUMP": 17, "AUX": 18, "PRECOMPILE_DATA": 19,
}


def _eval_air_execution(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    up = folder.up
    down = folder.down
    one = EF.one()

    next_pc = down[0]
    next_fp = down[1]

    operand_a = up[_EXEC["OPERAND_A"]]
    operand_b = up[_EXEC["OPERAND_B"]]
    operand_c = up[_EXEC["OPERAND_C"]]
    flag_a = up[_EXEC["FLAG_A"]]
    flag_b = up[_EXEC["FLAG_B"]]
    flag_c = up[_EXEC["FLAG_C"]]
    flag_c_fp = up[_EXEC["FLAG_C_FP"]]
    flag_ab_fp = up[_EXEC["FLAG_AB_FP"]]
    mul = up[_EXEC["MUL"]]
    jump = up[_EXEC["JUMP"]]
    aux = up[_EXEC["AUX"]]
    precompile_data = up[_EXEC["PRECOMPILE_DATA"]]

    value_a = up[_EXEC["MEM_VALUE_A"]]
    value_b = up[_EXEC["MEM_VALUE_B"]]
    value_c = up[_EXEC["MEM_VALUE_C"]]
    pc = up[_EXEC["PC"]]
    fp = up[_EXEC["FP"]]
    addr_a = up[_EXEC["MEM_ADDRESS_A"]]
    addr_b = up[_EXEC["MEM_ADDRESS_B"]]
    addr_c = up[_EXEC["MEM_ADDRESS_C"]]

    one_minus_flag_a_and_flag_ab_fp = -(flag_a + flag_ab_fp - one)
    one_minus_flag_b_and_flag_ab_fp = -(flag_b + flag_ab_fp - one)
    one_minus_flag_c_and_flag_c_fp = -(flag_c + flag_c_fp - one)

    nu_a = (
        flag_a * operand_a
        + one_minus_flag_a_and_flag_ab_fp * value_a
        + flag_ab_fp * (fp + operand_a)
    )
    nu_b = (
        flag_b * operand_b
        + one_minus_flag_b_and_flag_ab_fp * value_b
        + flag_ab_fp * (fp + operand_b)
    )
    nu_c = (
        flag_c * operand_c
        + one_minus_flag_c_and_flag_c_fp * value_c
        + flag_c_fp * (fp + operand_c)
    )

    fp_plus_op_a = fp + operand_a
    fp_plus_op_b = fp + operand_b
    fp_plus_op_c = fp + operand_c
    pc_plus_one = pc + one
    nu_a_minus_one = nu_a - one

    add = aux * EF.from_base(Fp(2)) - aux * aux
    deref = aux * (aux - one) * EF.from_base(_INV_TWO)
    is_precompile = -(add + mul + deref + jump - one)

    # Constraint 1: bus column (assert_zero_ef)
    folder.assert_zero_ef(
        _eval_virtual_bus_column(
            extra_data, is_precompile, [precompile_data, nu_a, nu_b, nu_c]
        )
    )

    # Constraints 2-4: address consistency
    folder.assert_zero(one_minus_flag_a_and_flag_ab_fp * (addr_a - fp_plus_op_a))
    folder.assert_zero(one_minus_flag_b_and_flag_ab_fp * (addr_b - fp_plus_op_b))
    folder.assert_zero(one_minus_flag_c_and_flag_c_fp * (addr_c - fp_plus_op_c))

    # Constraints 5-6: add/mul
    folder.assert_zero(add * (nu_b - (nu_a + nu_c)))
    folder.assert_zero(mul * (nu_b - nu_a * nu_c))

    # Constraints 7-8: deref
    folder.assert_zero(deref * (addr_b - (value_a + operand_b)))
    folder.assert_zero(deref * (value_b - nu_c))

    # Constraints 9-13: jump
    jump_and_condition = jump * nu_a
    folder.assert_zero(jump_and_condition * nu_a_minus_one)
    folder.assert_zero(jump_and_condition * (next_pc - nu_b))
    folder.assert_zero(jump_and_condition * (next_fp - nu_c))
    not_jump_and_condition = -(jump_and_condition - one)
    folder.assert_zero(not_jump_and_condition * (next_pc - pc_plus_one))
    folder.assert_zero(not_jump_and_condition * (next_fp - fp))



# ─── Extension-op-table AIR (lean_vm/src/tables/extension_op/air.rs) ──────────────────────────────────────────────────────────


_EXT_OP_COL = {
    "IS_BE": 0, "START": 1, "FLAG_ADD": 2, "FLAG_MUL": 3, "FLAG_POLY_EQ": 4,
    "LEN": 5, "IDX_A": 6, "IDX_B": 7, "IDX_RES": 8,
    "VA": 9, "VB": 14, "VRES": 19, "COMP": 24,
}

_EXT_OP_FLAG_IS_BE = 4
_EXT_OP_FLAG_ADD = 8
_EXT_OP_FLAG_MUL = 16
_EXT_OP_FLAG_POLY_EQ = 32
_EXT_OP_LEN_MULTIPLIER = 64


def _quintic_mul_ef(a: Sequence[EF], b: Sequence[EF]) -> list[EF]:
    """Quintic-extension multiplication on 5-element EF arrays.

    Direct port of `quintic_mul` from koalabear/quintic_extension/extension.rs
    using EF-level arithmetic — the dot-product becomes `Σ a[i]·b'[i]`.
    """
    assert len(a) == 5 and len(b) == 5
    b0m3 = b[0] - b[3]
    b1m4 = b[1] - b[4]
    b4m2 = b[4] - b[2]

    def dot(av: Sequence[EF], bv: Sequence[EF]) -> EF:
        acc = EF.zero()
        for x, y in zip(av, bv):
            acc = acc + x * y
        return acc

    return [
        dot(a, [b[0], b[4], b[3], b[2], b1m4]),
        dot(a, [b[1], b[0], b[4], b[3], b[2]]),
        dot(a, [b[2], b1m4, b0m3, b4m2, b[3] - b1m4]),
        dot(a, [b[3], b[2], b1m4, b0m3, b4m2]),
        dot(a, [b[4], b[3], b[2], b1m4, b0m3]),
    ]


def _eval_air_extension_op(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    up = folder.up
    down = folder.down
    one = EF.one()

    is_be = up[_EXT_OP_COL["IS_BE"]]
    start = up[_EXT_OP_COL["START"]]
    flag_add = up[_EXT_OP_COL["FLAG_ADD"]]
    flag_mul = up[_EXT_OP_COL["FLAG_MUL"]]
    flag_poly_eq = up[_EXT_OP_COL["FLAG_POLY_EQ"]]
    len_col = up[_EXT_OP_COL["LEN"]]
    idx_a = up[_EXT_OP_COL["IDX_A"]]
    idx_b = up[_EXT_OP_COL["IDX_B"]]
    idx_res = up[_EXT_OP_COL["IDX_RES"]]

    va = [up[_EXT_OP_COL["VA"] + k] for k in range(5)]
    vb = [up[_EXT_OP_COL["VB"] + k] for k in range(5)]
    vres = [up[_EXT_OP_COL["VRES"] + k] for k in range(5)]
    comp = [up[_EXT_OP_COL["COMP"] + k] for k in range(5)]

    start_down = down[0]
    is_be_down = down[1]
    len_down = down[2]
    flag_add_down = down[3]
    flag_mul_down = down[4]
    flag_poly_eq_down = down[5]
    idx_a_down = down[6]
    idx_b_down = down[7]
    comp_down = [down[8 + k] for k in range(5)]

    active = flag_add + flag_mul + flag_poly_eq
    activation_flag = start * active

    aux = (
        is_be * EF.from_base(Fp(_EXT_OP_FLAG_IS_BE))
        + flag_add * EF.from_base(Fp(_EXT_OP_FLAG_ADD))
        + flag_mul * EF.from_base(Fp(_EXT_OP_FLAG_MUL))
        + flag_poly_eq * EF.from_base(Fp(_EXT_OP_FLAG_POLY_EQ))
        + len_col * EF.from_base(Fp(_EXT_OP_LEN_MULTIPLIER))
    )

    # Constraint 1: bus
    folder.assert_zero_ef(
        _eval_virtual_bus_column(extra_data, activation_flag, [aux, idx_a, idx_b, idx_res])
    )

    is_ee = -(is_be - one)
    not_start_down = -(start_down - one)

    va_f_or_ef = [va[0]] + [va[k] * is_ee for k in range(1, 5)]
    comp_tail = [comp_down[k] * not_start_down for k in range(5)]

    # Constraints 2-6: bool flags
    folder.assert_bool(is_be)
    folder.assert_bool(start)
    folder.assert_bool(flag_add)
    folder.assert_bool(flag_mul)
    folder.assert_bool(flag_poly_eq)

    # Constraints 7-11: add
    for k in range(5):
        folder.assert_zero((comp[k] - (va_f_or_ef[k] + vb[k] + comp_tail[k])) * flag_add)

    va_times_vb = _quintic_mul_ef(va_f_or_ef, vb)

    # Constraints 12-16: mul
    for k in range(5):
        folder.assert_zero((comp[k] - (va_times_vb[k] + comp_tail[k])) * flag_mul)

    # Constraints 17-21: poly_eq
    poly_eq_val = []
    for k in range(5):
        base = va_times_vb[k] + va_times_vb[k] - va_f_or_ef[k] - vb[k]
        poly_eq_val.append(base + one if k == 0 else base)
    comp_down_or_one = []
    for k in range(5):
        if k == 0:
            comp_down_or_one.append(comp_down[0] * not_start_down + start_down)
        else:
            comp_down_or_one.append(comp_down[k] * not_start_down)
    poly_eq_result = _quintic_mul_ef(poly_eq_val, comp_down_or_one)
    for k in range(5):
        folder.assert_zero((comp[k] - poly_eq_result[k]) * flag_poly_eq)

    # Constraints 22-26: result matches comp when start
    for k in range(5):
        folder.assert_zero((comp[k] - vres[k]) * start)

    # Constraints 27-31: down-row consistency on non-start rows
    folder.assert_zero(not_start_down * (len_col - len_down - one))
    folder.assert_zero(not_start_down * (is_be - is_be_down))
    folder.assert_zero(not_start_down * (flag_add - flag_add_down))
    folder.assert_zero(not_start_down * (flag_mul - flag_mul_down))
    folder.assert_zero(not_start_down * (flag_poly_eq - flag_poly_eq_down))

    # Constraint 32-33: idx_a / idx_b increment
    a_increment = is_be + is_ee * EF.from_base(Fp(5))  # DIMENSION = 5
    folder.assert_zero(not_start_down * (idx_a_down - idx_a - a_increment))
    folder.assert_zero(not_start_down * (idx_b_down - idx_b - EF.from_base(Fp(5))))

    # Constraint 34: start_down enforces len=1
    folder.assert_zero(start_down * (len_col - one))



# ─── Poseidon16-compress AIR (lean_vm/src/tables/poseidon_16/mod.rs) ──────────────────────────────────────────────────────────


def _ef_cube(x: EF) -> EF:
    return x * x * x


@functools.cache
def _p1c() -> dict:
    """Poseidon1 round constants + matrices, lifted from the Rust-dumped JSON."""
    import json
    from pathlib import Path
    raw = json.loads(Path(__file__).with_name("poseidon1_constants.json").read_text())
    mat = lambda m: [[Fp(v) for v in row] for row in m]
    vec = lambda v: [Fp(x) for x in v]
    return {
        "half_full_rounds":  raw["half_full_rounds"],
        "partial_rounds":    raw["partial_rounds"],
        "initial_constants": mat(raw["initial_constants"]),
        "final_constants":   mat(raw["final_constants"]),
        "sparse_m_i":        mat(raw["sparse_m_i"]),
        "sparse_first_row":  mat(raw["sparse_first_row"]),
        "sparse_v":          mat(raw["sparse_v"]),
        "sparse_first_rc":   vec(raw["sparse_first_round_constants"]),
        "sparse_scalar_rc":  vec(raw["sparse_scalar_round_constants"]),
        "mds_dense":         mat(raw["mds_dense"]),
    }


_POSEIDON_WIDTH = 16
_HALF_DIGEST_LEN = 4
_POSEIDON_HALF_OUTPUT_SHIFT = 1 << 1            # = 2
_POSEIDON_HARDCODED_LEFT_4_FLAG_SHIFT = 1 << 2  # = 4
_POSEIDON_HARDCODED_LEFT_4_OFFSET_SHIFT = 1 << 3  # = 8


def _mds_dense_apply(state: list[EF]) -> list[EF]:
    """state := mds_dense × state (dense MDS matrix multiplication)."""
    mds = _p1c()["mds_dense"]
    out: list[EF] = []
    for i in range(_POSEIDON_WIDTH):
        acc = EF.zero()
        for j in range(_POSEIDON_WIDTH):
            acc = acc + state[j] * mds[i][j]
        out.append(acc)
    return out


def _add_kb_vec(state: list[EF], rc: list[Fp]) -> list[EF]:
    return [s + EF.from_base(r) for s, r in zip(state, rc)]


def _cube_vec(state: list[EF]) -> list[EF]:
    return [_ef_cube(s) for s in state]


def _eval_2_full_rounds(
    folder: ConstraintFolder,
    state: list[EF],
    post_full_round: Sequence[EF],
    rc1: list[Fp],
    rc2: list[Fp],
) -> list[EF]:
    state = _cube_vec(_add_kb_vec(state, rc1))
    state = _mds_dense_apply(state)
    state = _cube_vec(_add_kb_vec(state, rc2))
    state = _mds_dense_apply(state)
    for i in range(_POSEIDON_WIDTH):
        folder.assert_eq(state[i], post_full_round[i])
        state[i] = post_full_round[i]
    return state


def _eval_last_2_full_rounds(
    folder: ConstraintFolder,
    initial_state: Sequence[EF],
    state: list[EF],
    outputs: Sequence[EF],
    rc1: list[Fp],
    rc2: list[Fp],
    flag_half_output: EF,
) -> None:
    state = _cube_vec(_add_kb_vec(state, rc1))
    state = _mds_dense_apply(state)
    state = _cube_vec(_add_kb_vec(state, rc2))
    state = _mds_dense_apply(state)
    # Davies-Meyer: state += initial_state.
    state = [s + init for s, init in zip(state, initial_state)]
    one_minus_half = EF.one() - flag_half_output
    for idx in range(_POSEIDON_WIDTH // 2):
        if idx < _HALF_DIGEST_LEN:
            folder.assert_eq(state[idx], outputs[idx])
        else:
            folder.assert_zero(one_minus_half * (state[idx] - outputs[idx]))


def _eval_poseidon1_16(folder: ConstraintFolder, cols: dict, extra_data: dict) -> None:
    const = _p1c()
    state = list(cols["inputs"])
    initial_state = list(cols["inputs"])  # used for compression at the end

    # --- initial full rounds (HALF_INITIAL_FULL_ROUNDS = 2) ---
    half_initial = const["half_full_rounds"] // 2
    initial_consts = const["initial_constants"]
    for r in range(half_initial):
        state = _eval_2_full_rounds(
            folder, state, cols["beginning_full_rounds"][r],
            initial_consts[2 * r], initial_consts[2 * r + 1],
        )

    # --- transition into partial rounds (no constraints emitted here) ---
    # Rust uses the sparse `m_i` matrix, NOT the dense MDS.
    state = _add_kb_vec(state, const["sparse_first_rc"])
    state = _matvec_kb(const["sparse_m_i"], state)

    first_rows = const["sparse_first_row"]
    v_vecs = const["sparse_v"]
    scalar_rc = const["sparse_scalar_rc"]
    n_partial = const["partial_rounds"]
    for r in range(n_partial):
        # S-box on state[0]; the cubed value is committed in `partial_rounds[r]`.
        cubed = _ef_cube(state[0])
        folder.assert_eq(cubed, cols["partial_rounds"][r])  # assert_eq_low ≡ assert_eq
        state[0] = cols["partial_rounds"][r]
        if r < n_partial - 1:
            state[0] = state[0] + scalar_rc[r]
        # Sparse mat: new_s0 = first_row[r] · state; state[i] += old_s0 * v[r][i-1].
        old_s0 = state[0]
        new_s0 = EF.zero()
        for j in range(_POSEIDON_WIDTH):
            new_s0 = new_s0 + state[j] * first_rows[r][j]
        state[0] = new_s0
        for i in range(1, _POSEIDON_WIDTH):
            state[i] = state[i] + old_s0 * v_vecs[r][i - 1]

    # --- ending full rounds (HALF_FINAL_FULL_ROUNDS - 1 = 1) ---
    half_final = const["half_full_rounds"] // 2
    final_consts = const["final_constants"]
    for r in range(half_final - 1):
        state = _eval_2_full_rounds(
            folder, state, cols["ending_full_rounds"][r],
            final_consts[2 * r], final_consts[2 * r + 1],
        )

    # --- last 2 full rounds (8 constraints) ---
    last_idx = 2 * (half_final - 1)
    _eval_last_2_full_rounds(
        folder, initial_state, state, cols["outputs"],
        final_consts[last_idx], final_consts[last_idx + 1],
        cols["flag_half_output"],
    )


def _matvec_kb(mat: list[list[Fp]], state: list[EF]) -> list[EF]:
    """16x16 base-field matrix · EF-vector."""
    out = []
    for i in range(_POSEIDON_WIDTH):
        acc = EF.zero()
        for j in range(_POSEIDON_WIDTH):
            acc = acc + state[j] * mat[i][j]
        out.append(acc)
    return out


def _eval_air_poseidon16(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    up = folder.up
    one = EF.one()
    const = _p1c()

    # Decode the Poseidon1Cols16 layout.
    o = 0
    flag_active = up[o]; o += 1
    index_b = up[o]; o += 1
    index_res = up[o]; o += 1
    flag_half_output = up[o]; o += 1
    flag_hardcoded_left = up[o]; o += 1
    offset_hardcoded_left = up[o]; o += 1
    effective_index_left_first = up[o]; o += 1
    effective_index_left_second = up[o]; o += 1
    inputs = up[o : o + _POSEIDON_WIDTH]; o += _POSEIDON_WIDTH
    half_initial = const["half_full_rounds"] // 2
    beginning_full_rounds = []
    for _ in range(half_initial):
        beginning_full_rounds.append(up[o : o + _POSEIDON_WIDTH])
        o += _POSEIDON_WIDTH
    partial_cols = up[o : o + const["partial_rounds"]]; o += const["partial_rounds"]
    half_final = const["half_full_rounds"] // 2
    ending_full_rounds = []
    for _ in range(half_final - 1):
        ending_full_rounds.append(up[o : o + _POSEIDON_WIDTH])
        o += _POSEIDON_WIDTH
    outputs = up[o : o + _POSEIDON_WIDTH // 2]; o += _POSEIDON_WIDTH // 2

    precompile_data_reconstructed = (
        one
        + flag_half_output * EF.from_base(Fp(_POSEIDON_HALF_OUTPUT_SHIFT))
        + flag_hardcoded_left * EF.from_base(Fp(_POSEIDON_HARDCODED_LEFT_4_FLAG_SHIFT))
        + flag_hardcoded_left
        * offset_hardcoded_left
        * EF.from_base(Fp(_POSEIDON_HARDCODED_LEFT_4_OFFSET_SHIFT))
    )

    one_minus_flag_hardcoded_left = one - flag_hardcoded_left
    index_a = effective_index_left_second - one_minus_flag_hardcoded_left * EF.from_base(
        Fp(_HALF_DIGEST_LEN)
    )

    # Constraint 1: bus
    folder.assert_zero_ef(
        _eval_virtual_bus_column(
            extra_data, flag_active, [precompile_data_reconstructed, index_a, index_b, index_res]
        )
    )

    # Constraints 2-4: bool flags
    folder.assert_bool(flag_active)
    folder.assert_bool(flag_half_output)
    folder.assert_bool(flag_hardcoded_left)

    # Constraints 5-6: hardcoded-left consistency
    folder.assert_zero(
        flag_hardcoded_left * (offset_hardcoded_left - effective_index_left_first)
    )
    folder.assert_zero(
        one_minus_flag_hardcoded_left * (index_a - effective_index_left_first)
    )

    _eval_poseidon1_16(
        folder,
        {
            "inputs": list(inputs),
            "beginning_full_rounds": [list(r) for r in beginning_full_rounds],
            "partial_rounds": list(partial_cols),
            "ending_full_rounds": [list(r) for r in ending_full_rounds],
            "outputs": list(outputs),
            "flag_half_output": flag_half_output,
        },
        extra_data,
    )



# ─── AIR-stage orchestration in verify_execution ──────────────────────────────────────────────────────────


@dataclass
class AirStageResult:
    """Outputs of the AIR sumcheck stage, fed into the WHIR finale."""

    committed_statements: dict[str, list[tuple[list[EF], dict[int, EF], dict[int, EF]]]]
    public_memory_random_point: list[EF]
    public_memory_eval: EF


# Per-table compile-time spec (Rust: `<Table as Air>::{degree_air, n_constraints,
# down_column_indexes}`). The down-column lists for `execution` and
# `extension_op` are exactly what their `Air::down_column_indexes` returns.
_TABLE_SPECS: dict[str, dict] = {
    "execution":           {"degree": 5,  "n_constraints": 13, "down": [0, 1]},
    "extension_op":        {"degree": 4,  "n_constraints": 16, "down": [1, 0, 5, 2, 3, 4, 6, 7, 24, 25, 26, 27, 28]},
    "poseidon16_compress": {"degree": 10, "n_constraints": 81, "down": []},
}


def verify_air_stage(
    state: VerifierState,
    logup: GenericLogupStatements,
    logup_c: EF,
    logup_alphas_eq_poly: list[EF],
    table_log_heights: dict[str, int],
    tables: dict[str, TableMeta],
    public_input: Sequence[Fp],
    log_memory: int,
) -> AirStageResult:
    """Returns the per-table committed statements (point + eq_values + next_values)
    and the public-memory random point + its evaluation.
    """
    bus_beta = state.sample()
    air_alpha = state.sample()

    max_n_constraints = max(_TABLE_SPECS[name]["n_constraints"] for name in tables)
    alpha_powers: list[EF] = []
    cur = EF.one()
    for _ in range(max_n_constraints + 1):
        alpha_powers.append(cur)
        cur = cur * air_alpha

    eta = state.sample()

    tables_sorted = sort_tables_by_height(table_log_heights)

    # Build initial_sum.
    initial_sum = EF.zero()
    eta_powers: list[EF] = []
    cur = EF.one()
    for name, _ in tables_sorted:
        bus_num = logup.bus_numerators_values[name]
        bus_den = logup.bus_denominators_values[name]
        flag = (
            EF.zero() - EF.one()
            if tables[name].bus_direction == "Pull"
            else EF.one()
        )
        bus_final_value = bus_num * flag + bus_beta * (bus_den - logup_c)
        initial_sum = initial_sum + cur * bus_final_value
        eta_powers.append(cur)
        cur = cur * eta

    max_full_degree = max(_TABLE_SPECS[name]["degree"] + 1 for name, _ in tables_sorted)
    n_max = tables_sorted[0][1]

    sumcheck_result = sumcheck_verify(state, n_max, max_full_degree, initial_sum)
    sumcheck_air_point = sumcheck_result.point
    claimed_air_final_value = sumcheck_result.value

    # Per-table loop: read col_evals, evaluate AIR, accumulate, build claims.
    my_air_final_value = EF.zero()

    # Seed committed_statements with the logup entry per table, mirroring the
    # init loop in `verify_execution.rs` (lines 88-98).
    committed: dict[str, list[tuple[list[EF], dict[int, EF], dict[int, EF]]]] = {}
    for name in tables:
        log_n = table_log_heights[name]
        logup_point = from_end(logup.gkr_point, log_n)
        committed[name] = [
            (list(logup_point), dict(logup.columns_values[name]), {}),
        ]
    extra_data = {
        "logup_alphas_eq_poly": logup_alphas_eq_poly,
        "bus_beta": bus_beta,
        "c": logup_c,
    }
    for (name, log_n_rows), eta_pow in zip(tables_sorted, eta_powers):
        meta = tables[name]
        down_indexes = _TABLE_SPECS[name]["down"]
        col_evals = state.next_extension_scalars_vec(meta.n_columns + len(down_indexes))
        constraint_eval = air_constraint_eval(meta, col_evals, alpha_powers, extra_data)

        bus_point = from_end(logup.gkr_point, log_n_rows)
        natural_pt = natural_ordering_point_for_session(sumcheck_air_point, log_n_rows)
        my_air_final_value = my_air_final_value + back_loaded_table_contribution(
            bus_point, sumcheck_air_point, natural_pt, constraint_eval, eta_pow
        )

        point, eq_values, next_values = columns_evals_up_and_down(
            meta.n_columns, down_indexes, col_evals, natural_pt
        )
        committed[name].append((point, eq_values, next_values))

    if my_air_final_value != claimed_air_final_value:
        raise ProofError("AIR sumcheck: my_air_final_value != claimed_air_final_value")

    # Public memory evaluation (length is next power of two of public_input).
    public_memory = padd_with_zero_to_next_power_of_two(public_input)
    log_pm = log2_strict_usize(len(public_memory))
    public_memory_random_point = state.sample_vec(log_pm)
    public_memory_eval = eval_multilinear_evals(
        [EF.from_base(f) for f in public_memory], public_memory_random_point
    )

    return AirStageResult(
        committed_statements=committed,
        public_memory_random_point=list(public_memory_random_point),
        public_memory_eval=public_memory_eval,
    )



# ─── Top-level verifier ──────────────────────────────────────────────────────────


@dataclass
class VerifyResult:
    """High-level outputs of `verify_execution` (mostly for diagnostics)."""

    log_inv_rate: int
    log_memory: int
    stacked_n_vars: int
    bytecode_evaluation_point: list[EF]
    bytecode_evaluation_value: EF


def verify_execution(
    bytecode: Bytecode,
    public_input: Sequence[Fp],
    proof: Proof,
    tables: Sequence[TableMeta],
    constants: dict,
    bytecode_multilinear: list[Fp],
) -> VerifyResult:
    """Verify a leanVM execution proof. Port of `verify_execution.rs`.

    The flow is:
        1. observe public input + SNARK domain separator
        2. read dims, validate bounds
        3. parse stacked-PCS WHIR commitment (root + OOD)
        4. verify generic logup (GKR + sum reconstruction)
        5. AIR sumcheck across all tables + per-table constraint evaluation
        6. assemble global WHIR statements and run the final WHIR verify

    `tables` must be in canonical Rust order (= `ALL_TABLES`): execution,
    extension_op, poseidon16. `constants` and `bytecode_multilinear` come from
    the Rust dump.
    """

    state = VerifierState(proof)
    state.observe_scalars(list(public_input))
    state.observe_scalars(poseidon16_compress(bytecode.hash, SNARK_DOMAIN_SEP))

    n_tables = len(tables)
    dims = [int(x.value) for x in state.next_base_scalars_vec(3 + n_tables)]
    log_inv_rate, log_memory, public_input_len = dims[0], dims[1], dims[2]
    table_log_n_rows = dims[3 : 3 + n_tables]

    if public_input_len != len(public_input):
        raise ProofError("InvalidProof: public_input length mismatch")

    if not (MIN_WHIR_LOG_INV_RATE <= log_inv_rate <= MAX_WHIR_LOG_INV_RATE):
        raise ProofError("InvalidRate")

    for log_n_rows in table_log_n_rows:
        if log_n_rows < MIN_LOG_N_ROWS_PER_TABLE:
            raise ProofError("InvalidProof: table too small")

    max_table_log = max(table_log_n_rows) if table_log_n_rows else 0
    if log_memory < max(max_table_log, bytecode.log_size):
        raise ProofError("InvalidProof: memory smaller than tables/bytecode")

    if not (MIN_LOG_MEMORY_SIZE <= log_memory <= MAX_LOG_MEMORY_SIZE):
        raise ProofError("InvalidProof: log_memory out of range")

    if bytecode.log_size < MIN_BYTECODE_LOG_SIZE:
        raise ProofError("InvalidProof: bytecode too small")

    table_log_heights = {t.name: log_n_rows for t, log_n_rows in zip(tables, table_log_n_rows)}
    table_n_columns = {t.name: t.n_columns for t in tables}
    tables_by_name = {t.name: t for t in tables}

    parsed_commitment = stacked_pcs_parse_commitment(
        state,
        log_inv_rate=log_inv_rate,
        log_memory=log_memory,
        log_bytecode=bytecode.log_size,
        table_log_heights=table_log_heights,
        table_n_columns=table_n_columns,
    )

    # Logup challenges.
    logup_c = state.sample()
    max_bus_width = 1 + max(
        constants["max_precompile_bus_width"], constants["n_instruction_columns"]
    )
    logup_alphas = state.sample_vec(log2_ceil_usize(max_bus_width))
    logup_alphas_eq_poly = eval_eq(logup_alphas)

    logup_statements = verify_generic_logup(
        state,
        logup_c,
        logup_alphas,
        logup_alphas_eq_poly,
        log_memory,
        bytecode_multilinear,
        table_log_heights,
        tables_by_name,
        constants,
    )

    air_stage = verify_air_stage(
        state,
        logup_statements,
        logup_c,
        logup_alphas_eq_poly,
        table_log_heights,
        tables_by_name,
        public_input,
        log_memory,
    )

    # Build the global WHIR statement list and run the final WHIR verify.
    stacked_n_vars = parsed_commitment.num_variables
    previous_statements = [
        SparseStatement(
            total_num_variables=stacked_n_vars,
            point=list(logup_statements.memory_and_acc_point),
            values=[
                SparseValue(0, logup_statements.value_memory),
                SparseValue(1, logup_statements.value_memory_acc),
            ],
            is_next=False,
        ),
        SparseStatement(
            total_num_variables=stacked_n_vars,
            point=list(air_stage.public_memory_random_point),
            values=[SparseValue(0, air_stage.public_memory_eval)],
            is_next=False,
        ),
        SparseStatement(
            total_num_variables=stacked_n_vars,
            point=list(logup_statements.bytecode_and_acc_point),
            values=[
                SparseValue(
                    (2 << log_memory) >> bytecode.log_size,
                    logup_statements.value_bytecode_acc,
                ),
            ],
            is_next=False,
        ),
    ]

    global_statements = stacked_pcs_global_statements(
        stacked_n_vars,
        log_memory,
        bytecode.log_size,
        previous_statements,
        table_log_heights,
        air_stage.committed_statements,
        tables_by_name,
        constants,
    )

    whir_cfg = whir_config(log_inv_rate, stacked_n_vars)
    whir_verify(state, whir_cfg, parsed_commitment, global_statements)

    return VerifyResult(
        log_inv_rate=log_inv_rate,
        log_memory=log_memory,
        stacked_n_vars=stacked_n_vars,
        bytecode_evaluation_point=list(logup_statements.bytecode_evaluation.point),
        bytecode_evaluation_value=logup_statements.bytecode_evaluation.value,
    )



# ─── Test vector loader + entry point ──────────────────────────────────────────────────────────


def poseidon_compress_slice(data: Sequence[Fp], use_iv: bool) -> list[Fp]:
    """Hash a length-multiple-of-8 sequence into one 8-element digest using
    Poseidon16 in Davies-Meyer compression mode. If `use_iv` is false the
    first 16 elements seed the sponge directly; if true an all-zero IV is used.
    """
    assert data and len(data) % 8 == 0
    if use_iv:
        h = [Fp(0)] * 8
        for i in range(0, len(data), 8):
            h = poseidon16_compress(h, list(data[i : i + 8]))
        return h
    if len(data) <= 16:
        padded = list(data) + [Fp(0)] * (16 - len(data))
        return poseidon16_compress_in_place(padded)[:8]
    h = poseidon16_compress_in_place(list(data[:16]))[:8]
    for i in range(16, len(data), 8):
        h = poseidon16_compress(h, list(data[i : i + 8]))
    return h


def main() -> int:
    """Load the end-to-end test vector and run `verify_execution`."""
    import array
    import json
    from pathlib import Path

    vector_path = Path(__file__).resolve().parents[2] / "target" / "zkvm_test_vectors" / "proof.json"
    if not vector_path.exists():
        print(
            f"Test vector not found at {vector_path}. Generate it first with:\n"
            "    cargo test --release -p lean_prover --test dump_zkvm_vector -- --nocapture"
        )
        return 1

    print(f"Loading {vector_path.name}...")
    raw = json.loads(vector_path.read_text())

    # Bytecode multilinear (raw u32 LE sidecar).
    mle_blob = (vector_path.parent / raw["bytecode_multilinear_path"]).read_bytes()
    arr = array.array("I"); arr.frombytes(mle_blob)
    assert len(arr) == raw["bytecode_multilinear_len"]
    bytecode_multilinear = [Fp(v) for v in arr]

    bytecode = Bytecode([Fp(v) for v in raw["bytecode_hash"]], raw["bytecode_log_size"])
    public_input = [Fp(v) for v in raw["public_input"]]
    input_data = [Fp(v) for v in raw["input_data"]]

    openings = [
        MerkleOpening(
            leaf_data=[Fp(v) for v in o["leaf_data"]],
            path=[[Fp(v) for v in d] for d in o["path"]],
        )
        for o in raw["proof"]["merkle_openings"]
    ]
    proof = Proof(transcript=[Fp(v) for v in raw["proof"]["transcript"]], merkle_openings=openings)

    # Sanity: re-derive `public_input` from `input_data` to check the hash.
    if poseidon_compress_slice(input_data, use_iv=True) != public_input:
        print("FAIL: poseidon_compress_slice(input_data) doesn't match dumped public_input")
        return 1

    try:
        result = verify_execution(
            bytecode, public_input, proof,
            tables_from_json(raw["tables"]), raw["constants"], bytecode_multilinear,
        )
    except ProofError as e:
        print(f"FAIL: {e}")
        return 1

    print(
        f"OK: rec-aggregation proof verified "
        f"(log_inv_rate={result.log_inv_rate}, log_memory={result.log_memory}, "
        f"stacked_n_vars={result.stacked_n_vars})"
    )
    return 0


if __name__ == "__main__":
    import sys as _sys
    _sys.exit(main())
