"""
Width-6 read-once branching program (ROBP) for the jagged-PCS indicator
polynomial `g_u(z_row, z_col, z_index, t_prev, t_next)`, ported from
`crates/sub_protocols/src/jagged_pcs/branching.rs` (the Rust verifier).

`g_u` returns 1 iff `i = t_prev + z_row * 2^u + z_col` (as integers) and
`i < t_next`. The MLE of this function over `m + 3m + n = O(m)` boolean
coordinates is what each jagged-PCS claim's "F(i*)" contribution
evaluates to.

State encoding: `s = carry + 3 * (lt as int)` with `carry in {0,1,2}`
(trit carry of `row + col + prev` mod p) and `lt in {0,1}` (whether the
bit prefix of `i` is < the bit prefix of `t_next`).
  s=0 INITIAL (carry=0, lt=0)
  s=1            (carry=1, lt=0)
  s=2            (carry=2, lt=0)
  s=3 SUCCESS  (carry=0, lt=1)
  s=4            (carry=1, lt=1)
  s=5            (carry=2, lt=1)

Per layer the BP reads a 5-bit combo packed as
`combo = (row<<4)|(col<<3)|(idx<<2)|(prev<<1)|next`. For each (source
state, combo) the transition either succeeds (yielding a destination
state) or fails (combo inconsistent with the addition mod 2).

The matched zkDSL semantics is:

    F(z_row, z_col, z_index, t_prev, t_next) =
        z_row_correction *
        sum_{(combos at each layer)} prod_layer eq(layer_bits, combo_bits) *
        1[the layer-by-layer state walk from SUCCESS back to INITIAL is consistent]

We unfold the right-hand side as the matrix-power formulation in
the Rust code: state_results starts as the SUCCESS-indicator vector,
then we apply m layer transitions, and the answer is the INITIAL slot
times the z_row_correction (the (1 - z_row[i]) factor for each MSB
position of z_row that the BP doesn't read).
"""

from utils import *

# Generated by `gen_bp.py`; see top-of-file comment for the encoding.
# For source state `s in [0, 6)`, `BP_COMBOS[s][k]` is the k-th 5-bit
# combo (in `[0, 32)`) for which the transition succeeds, and
# `BP_NEXT_STATES[s][k]` is the corresponding destination state.
# Exactly 16 valid combos per state (parity of `row + col + prev + carry`
# pins `idx`, leaving 4 free bits = 16 combos).
BP_COMBOS = [
    [0, 1, 6, 7, 10, 11, 12, 13, 18, 19, 20, 21, 24, 25, 30, 31],
    [2, 3, 4, 5, 8, 9, 14, 15, 16, 17, 22, 23, 26, 27, 28, 29],
    [0, 1, 6, 7, 10, 11, 12, 13, 18, 19, 20, 21, 24, 25, 30, 31],
    [0, 1, 6, 7, 10, 11, 12, 13, 18, 19, 20, 21, 24, 25, 30, 31],
    [2, 3, 4, 5, 8, 9, 14, 15, 16, 17, 22, 23, 26, 27, 28, 29],
    [0, 1, 6, 7, 10, 11, 12, 13, 18, 19, 20, 21, 24, 25, 30, 31],
]
BP_NEXT_STATES = [
    [0, 3, 0, 0, 1, 4, 0, 0, 1, 4, 0, 0, 1, 4, 1, 1],
    [1, 4, 0, 0, 1, 4, 1, 1, 1, 4, 1, 1, 2, 5, 1, 1],
    [1, 4, 1, 1, 2, 5, 1, 1, 2, 5, 1, 1, 2, 5, 2, 2],
    [3, 3, 0, 3, 4, 4, 0, 3, 4, 4, 0, 3, 4, 4, 1, 4],
    [4, 4, 0, 3, 4, 4, 1, 4, 4, 4, 1, 4, 5, 5, 1, 4],
    [4, 4, 1, 4, 5, 5, 1, 4, 5, 5, 1, 4, 5, 5, 2, 5],
]

BP_N_STATES = 6
BP_N_VALID_COMBOS = 16  # per source state
BP_INITIAL = 0
BP_SUCCESS = 3


def bp_eval(z_row, z_row_len, z_col, z_col_len, z_index, t_prev, t_next, log_width, log_dense_size):
    """
    Evaluate the jagged-PCS BP at `(z_row, z_col, z_index, t_prev, t_next)`.

    Inputs (all flat pointers, in big-endian-bit order, DIM EF elements
    per coordinate):
      z_row           : `z_row_len * DIM` general EF elements
      z_col           : `z_col_len * DIM` general EF elements
      z_index         : `log_dense_size * DIM` general EF elements
      t_prev, t_next  : `log_dense_size * DIM` EF elements, each entry
                        constrained to be in `{F::ZERO, F::ONE}`
                        (booleanity is enforced upstream by the caller)
      log_width       : runtime `usize` -- the sub-table's column-bit count
      log_dense_size  : runtime `usize` -- m (number of layers)

    Returns a pointer to a `DIM`-element EF holding the BP evaluation.
    """
    # ------------------------------------------------------------------
    # z_row_correction: product of `(1 - z_row[i])` over the leading MSB
    # positions of `z_row` that the BP doesn't read. Matches the
    # `z_row[..n_unread]` product in `branching.rs`.
    # ------------------------------------------------------------------
    bp_reads_z_row = log_dense_size - log_width
    n_unread: Imu
    # `checked_less_than(a, b)` returns 1 iff a < b, else 0.
    # We want n_unread = max(0, z_row_len - bp_reads_z_row), i.e. 0 when
    # z_row_len <= bp_reads_z_row, else z_row_len - bp_reads_z_row.
    if checked_less_than(bp_reads_z_row, z_row_len) == 1:
        n_unread = z_row_len - bp_reads_z_row
    else:
        n_unread = 0

    z_row_correction: Mut = ONE_EF_PTR
    for i in range(0, n_unread):
        delta = sub_extension_ret(ONE_EF_PTR, z_row + i * DIM)
        z_row_correction = mul_extension_ret(z_row_correction, delta)

    # ------------------------------------------------------------------
    # Initial state vector: state_results[SUCCESS] = 1, others = 0.
    # Fresh `Array(...)` memory is uninitialized; reads of uninit slots
    # are an error (not zero). We must therefore explicitly write every
    # slot. `set_to_5_zeros(a)` is an *assertion* (`a·1 == 0`), not a
    # setter, so we use per-element base-field assignment instead.
    # `EF::ONE` in basis-coefficient form is `[1, 0, 0, 0, 0]`, so only
    # the very first coord of the SUCCESS slot is non-zero.
    # ------------------------------------------------------------------
    state_results: Mut = Array(BP_N_STATES * DIM)
    for s in unroll(0, BP_N_STATES):
        if s == BP_SUCCESS:
            state_results[s * DIM] = 1
            for k in unroll(1, DIM):
                state_results[s * DIM + k] = 0
        else:
            for k in unroll(0, DIM):
                state_results[s * DIM + k] = 0

    # ------------------------------------------------------------------
    # Layer-by-layer transition (MSB-down to LSB).
    # ------------------------------------------------------------------
    for layer_inv in range(0, log_dense_size):
        layer = log_dense_size - 1 - layer_inv

        # Bit pointers. `lsb_be(point, p)` = `point[len - 1 - p]` if the
        # position is within the point's length, otherwise `F::ZERO`.
        # The zkDSL `if` only supports `==`/`!=`, so we route the
        # `(log_width <= layer && (layer-log_width) < z_row_len)` test
        # through `checked_less_than` (which returns 0/1).
        row_bit_ptr: Imu
        if checked_less_than(layer, log_width) == 1:
            row_bit_ptr = ZERO_VEC_PTR
        else:
            row_offset = layer - log_width
            if checked_less_than(row_offset, z_row_len) == 1:
                row_bit_ptr = z_row + (z_row_len - 1 - row_offset) * DIM
            else:
                row_bit_ptr = ZERO_VEC_PTR

        col_bit_ptr: Imu
        if checked_less_than(layer, z_col_len) == 1:
            col_bit_ptr = z_col + (z_col_len - 1 - layer) * DIM
        else:
            col_bit_ptr = ZERO_VEC_PTR

        idx_bit_ptr = z_index + (log_dense_size - 1 - layer) * DIM
        prev_bit_ptr = t_prev + (log_dense_size - 1 - layer) * DIM
        next_bit_ptr = t_next + (log_dense_size - 1 - layer) * DIM

        # Pack the 5 bits into a contiguous buffer for `eval_eq`.
        bits = Array(5 * DIM)
        copy_5(row_bit_ptr, bits + 0 * DIM)
        copy_5(col_bit_ptr, bits + 1 * DIM)
        copy_5(idx_bit_ptr, bits + 2 * DIM)
        copy_5(prev_bit_ptr, bits + 3 * DIM)
        copy_5(next_bit_ptr, bits + 4 * DIM)
        # 32 weights, one per (row, col, idx, prev, next) in {0,1}^5.
        weights = compute_eq_mle_extension(bits, 5)

        # Matrix-vector update via per-source-state dot-products. For each
        # source state s, gather the 16 (weight, state) pairs the BP
        # transition table says contribute, then a single `dot_product_ee`
        # gives `new_state_results[s]`.
        new_state_results = Array(BP_N_STATES * DIM)
        for s in unroll(0, BP_N_STATES):
            gathered_w = Array(BP_N_VALID_COMBOS * DIM)
            gathered_s = Array(BP_N_VALID_COMBOS * DIM)
            for k in unroll(0, BP_N_VALID_COMBOS):
                copy_5(weights + BP_COMBOS[s][k] * DIM, gathered_w + k * DIM)
                copy_5(state_results + BP_NEXT_STATES[s][k] * DIM, gathered_s + k * DIM)
            dot_product_ee(gathered_w, gathered_s, new_state_results + s * DIM, BP_N_VALID_COMBOS)

        state_results = new_state_results

    # ------------------------------------------------------------------
    # Final result: state_results[INITIAL] * z_row_correction.
    # ------------------------------------------------------------------
    result = mul_extension_ret(state_results + BP_INITIAL * DIM, z_row_correction)
    return result
