name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            features: "+avx2"
          - os: ubuntu-latest
            features: "+avx512f"
          - os: ubuntu-latest-arm64
            features: "+neon"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        id: rs-stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-${{ steps.rs-stable.outputs.rustc_hash }}-${{ matrix.os }}-${{ matrix.features }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Set flags
        run: |
          echo "RUSTFLAGS=-Ctarget-feature=${{ matrix.features }}" >> "$GITHUB_ENV"

      - name: Build
        run: cargo build --all --verbose --all-targets

      - name: Test
        run: cargo test --all --verbose

  lint:
    name: Formatting and Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
        id: rs-stable

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rust-${{ steps.rs-stable.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Clippy
        run: cargo +stable clippy --all-targets -- -D warnings

      - name: Format
        run: cargo +nightly fmt --all -- --check